/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI.admin;

import co.edu.unicauca.academicproject.GUI.controller.Admin.ControllerRequestCoordi;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUIRequestCoordinator extends javax.swing.JFrame {

    /**
     * Creates new form GUIRequestCoordinator
     */
    String token;
    public GUIRequestCoordinator(String token) {
        initComponents();
        this.token = token;
        ControllerRequestCoordi controllerRequestCoordi = new ControllerRequestCoordi(this);
    }

    public String getToken(){
        return token;
    }

    public JLabel getLabelNameCoordi(){
        return jLNombreCoordi;
    }

    public JTable getTableHistoryCoordi() {
        return jTableHistoryCoordi;
    }

    public JTable getTableSoliCoordi() {
        return jTableSoliCoordi;
    }

    public JButton getBtnProcesarSoli(){
        return jBtnProcesarSoli;
    }

    public JRadioButton getRBtnAceptar(){
        return jRBtnAceptar;
    }

    public JButton getBtnBackHomeWithLogin(){
        return jBtnBackHomeWithLogin;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPHead = new javax.swing.JPanel();
        iconLoginUser = new javax.swing.JLabel();
        jLTitittleLogin = new javax.swing.JLabel();
        jPButtom = new javax.swing.JPanel();
        jBtnBackHomeWithLogin = new javax.swing.JButton();
        jPContent = new javax.swing.JPanel();
        jPCoordi = new javax.swing.JPanel();
        jLCoordinator = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHistoryCoordi = new javax.swing.JTable();
        jPCoordiSinEstado = new javax.swing.JPanel();
        jLSolisSinAtender = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSoliCoordi = new javax.swing.JTable();
        jLNombreCoordi = new javax.swing.JLabel();
        jPValidarCoordi = new javax.swing.JPanel();
        jRBtnAceptar = new javax.swing.JRadioButton();
        jBtnProcesarSoli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Solicitudes coordinadores");
        setMinimumSize(new java.awt.Dimension(1020, 700));

        jPHead.setBackground(new java.awt.Color(15, 32, 65));
        jPHead.setForeground(new java.awt.Color(255, 255, 255));
        jPHead.setLayout(new java.awt.GridBagLayout());

        iconLoginUser.setBackground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setForeground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPHead.add(iconLoginUser, gridBagConstraints);

        jLTitittleLogin.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLTitittleLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLTitittleLogin.setText("Solicitudes de coordinadores - Sistema proyectos");
        jLTitittleLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLTitittleLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPHead.add(jLTitittleLogin, gridBagConstraints);

        jPButtom.setBackground(new java.awt.Color(15, 32, 65));
        jPButtom.setForeground(new java.awt.Color(255, 255, 255));
        jPButtom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jBtnBackHomeWithLogin.setBackground(new java.awt.Color(15, 32, 65));
        jBtnBackHomeWithLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/anterior (1).png"))); // NOI18N
        jBtnBackHomeWithLogin.setBorderPainted(false);
        jPButtom.add(jBtnBackHomeWithLogin);

        jPContent.setBackground(new java.awt.Color(15, 32, 65));
        jPContent.setForeground(new java.awt.Color(255, 255, 255));

        jPCoordi.setBackground(new java.awt.Color(255, 255, 255));

        jLCoordinator.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLCoordinator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCoordinator.setText("Historial de solicitudes de coordinarores:");
        jLCoordinator.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTableHistoryCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableHistoryCoordi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableHistoryCoordi.setShowGrid(true);
        jScrollPane1.setViewportView(jTableHistoryCoordi);

        javax.swing.GroupLayout jPCoordiLayout = new javax.swing.GroupLayout(jPCoordi);
        jPCoordi.setLayout(jPCoordiLayout);
        jPCoordiLayout.setHorizontalGroup(
            jPCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLCoordinator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCoordiLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1)
                .addGap(10, 10, 10))
        );
        jPCoordiLayout.setVerticalGroup(
            jPCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordiLayout.createSequentialGroup()
                .addComponent(jLCoordinator)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPCoordiSinEstado.setBackground(new java.awt.Color(255, 255, 255));

        jLSolisSinAtender.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLSolisSinAtender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSolisSinAtender.setText("Solicitudes ");
        jLSolisSinAtender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTableSoliCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableSoliCoordi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableSoliCoordi.setShowGrid(true);
        jScrollPane2.setViewportView(jTableSoliCoordi);

        javax.swing.GroupLayout jPCoordiSinEstadoLayout = new javax.swing.GroupLayout(jPCoordiSinEstado);
        jPCoordiSinEstado.setLayout(jPCoordiSinEstadoLayout);
        jPCoordiSinEstadoLayout.setHorizontalGroup(
            jPCoordiSinEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordiSinEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCoordiSinEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLSolisSinAtender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPCoordiSinEstadoLayout.setVerticalGroup(
            jPCoordiSinEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordiSinEstadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLSolisSinAtender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );

        jLNombreCoordi.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLNombreCoordi.setForeground(new java.awt.Color(255, 255, 255));
        jLNombreCoordi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLNombreCoordi.setText("NOMBRE COORDI");

        jPValidarCoordi.setBackground(new java.awt.Color(15, 32, 65));
        jPValidarCoordi.setLayout(new java.awt.GridLayout(2, 1, 10, 20));

        jRBtnAceptar.setBackground(new java.awt.Color(204, 255, 204));
        jRBtnAceptar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jRBtnAceptar.setText("Aceptar solicitud");
        jRBtnAceptar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jRBtnAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jRBtnAceptar.setIconTextGap(10);
        jPValidarCoordi.add(jRBtnAceptar);

        jBtnProcesarSoli.setBackground(new java.awt.Color(172, 0, 0));
        jBtnProcesarSoli.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jBtnProcesarSoli.setForeground(new java.awt.Color(255, 255, 255));
        jBtnProcesarSoli.setText("ACEPTAR");
        jBtnProcesarSoli.setMinimumSize(new java.awt.Dimension(50, 50));
        jPValidarCoordi.add(jBtnProcesarSoli);

        javax.swing.GroupLayout jPContentLayout = new javax.swing.GroupLayout(jPContent);
        jPContent.setLayout(jPContentLayout);
        jPContentLayout.setHorizontalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPCoordi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPCoordiSinEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPValidarCoordi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLNombreCoordi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPContentLayout.setVerticalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPCoordi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addComponent(jPCoordiSinEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLNombreCoordi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPValidarCoordi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, 1021, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLoginUser;
    private javax.swing.JButton jBtnBackHomeWithLogin;
    private javax.swing.JButton jBtnProcesarSoli;
    private javax.swing.JLabel jLCoordinator;
    private javax.swing.JLabel jLNombreCoordi;
    private javax.swing.JLabel jLSolisSinAtender;
    private javax.swing.JLabel jLTitittleLogin;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPCoordi;
    private javax.swing.JPanel jPCoordiSinEstado;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPValidarCoordi;
    private javax.swing.JRadioButton jRBtnAceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableHistoryCoordi;
    private javax.swing.JTable jTableSoliCoordi;
    // End of variables declaration//GEN-END:variables
}
