/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI;

import co.edu.unicauca.academicproject.GUI.controller.Home.ControllerHomeWithOutLog;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUIHomeWithOutLog extends javax.swing.JFrame {

    /**
     * Creates new form GUIHomeWithOutLog
     */
    public GUIHomeWithOutLog() {

        initComponents();
        ControllerHomeWithOutLog controller = new ControllerHomeWithOutLog(this);
    }

    public JButton getjBtnLoginU() {
        return jBtnLoginU;
    }

    public JButton getjBtnNewUser() {
        return jBtnNewUser;
    }

    public JLabel getLbLogin() {
        return lbLogin;
    }

    public JLabel getLbNewUser() {
        return lbNewUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPContent = new javax.swing.JPanel();
        jLTittleProjects = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjects = new javax.swing.JTable();
        jSeparator = new javax.swing.JSeparator();
        jPSearchBar = new javax.swing.JPanel();
        jCBSelecFilter = new javax.swing.JComboBox<>();
        jFieldSearchProyect = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jButtonQuitF = new javax.swing.JButton();
        jPHead1 = new javax.swing.JPanel();
        lbTitleProyect1 = new java.awt.Label();
        jPOpcLogin1 = new javax.swing.JPanel();
        jBtnNewUser = new javax.swing.JButton();
        jBtnLoginU = new javax.swing.JButton();
        lbNewUser = new javax.swing.JLabel();
        lbLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPContent.setBackground(new java.awt.Color(236, 230, 240));
        jPContent.setLayout(new javax.swing.BoxLayout(jPContent, javax.swing.BoxLayout.Y_AXIS));

        jLTittleProjects.setBackground(new java.awt.Color(236, 230, 240));
        jLTittleProjects.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLTittleProjects.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleProjects.setText("Proyectos disponibles");
        jLTittleProjects.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPContent.add(jLTittleProjects);

        jTableProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProjects);

        jPContent.add(jScrollPane1);

        jSeparator.setBackground(new java.awt.Color(236, 230, 240));
        jSeparator.setForeground(new java.awt.Color(204, 204, 204));

        jPSearchBar.setBackground(new java.awt.Color(236, 230, 240));
        jPSearchBar.setLayout(new java.awt.GridBagLayout());

        jCBSelecFilter.setBackground(new java.awt.Color(236, 230, 240));
        jCBSelecFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Nombre", "Por Compañia", "Por Estudiante" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPSearchBar.add(jCBSelecFilter, gridBagConstraints);

        jFieldSearchProyect.setBackground(new java.awt.Color(236, 230, 240));
        jFieldSearchProyect.setText("Ingrese un proyecto a buscar...");
        jFieldSearchProyect.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jFieldSearchProyect.setMinimumSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        jPSearchBar.add(jFieldSearchProyect, gridBagConstraints);

        jBtnSearch.setBackground(new java.awt.Color(236, 230, 240));
        jBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        jBtnSearch.setBorderPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPSearchBar.add(jBtnSearch, gridBagConstraints);

        jButtonQuitF.setText("Quitar filtro");
        jPSearchBar.add(jButtonQuitF, new java.awt.GridBagConstraints());
        jButtonQuitF.setVisible(false);

        jPHead1.setBackground(new java.awt.Color(236, 230, 240));
        jPHead1.setLayout(new javax.swing.BoxLayout(jPHead1, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbTitleProyect1.setText("Sistema gestor de proyectos academicos");
        jPHead1.add(lbTitleProyect1);

        jPOpcLogin1.setBackground(new java.awt.Color(236, 230, 240));
        jPOpcLogin1.setLayout(new java.awt.GridLayout(2, 2, 10, 0));

        jBtnNewUser.setBackground(new java.awt.Color(236, 230, 240));
        jBtnNewUser.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jBtnNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/NewUser.png"))); // NOI18N
        jBtnNewUser.setToolTipText("");
        jBtnNewUser.setBorder(null);
        jBtnNewUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnNewUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnNewUser.setOpaque(true);
        jBtnNewUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPOpcLogin1.add(jBtnNewUser);

        jBtnLoginU.setBackground(new java.awt.Color(236, 230, 240));
        jBtnLoginU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LoginUser2.png"))); // NOI18N
        jBtnLoginU.setBorder(null);
        jBtnLoginU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnLoginU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLoginU.setIconTextGap(5);
        jBtnLoginU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnLoginU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcLogin1.add(jBtnLoginU);

        lbNewUser.setBackground(new java.awt.Color(101, 85, 153));
        lbNewUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbNewUser.setForeground(new java.awt.Color(255, 255, 255));
        lbNewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNewUser.setText("¿ Nuevo usuario ?");
        lbNewUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbNewUser.setOpaque(true);
        jPOpcLogin1.add(lbNewUser);

        lbLogin.setBackground(new java.awt.Color(101, 85, 153));
        lbLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(255, 255, 255));
        lbLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogin.setText("Iniciar Sesion");
        lbLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbLogin.setOpaque(true);
        jPOpcLogin1.add(lbLogin);

        jPHead1.add(jPOpcLogin1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
            .addComponent(jPSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLoginU;
    private javax.swing.JButton jBtnNewUser;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jButtonQuitF;
    private javax.swing.JComboBox<String> jCBSelecFilter;
    private javax.swing.JTextField jFieldSearchProyect;
    private javax.swing.JLabel jLTittleProjects;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead1;
    private javax.swing.JPanel jPOpcLogin1;
    private javax.swing.JPanel jPSearchBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTable jTableProjects;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbNewUser;
    private java.awt.Label lbTitleProyect1;
    // End of variables declaration//GEN-END:variables
}
