/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI;

import co.edu.unicauca.academicproject.GUI.controller.Home.ControllerHomeWithLog;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUIHomeWithLog extends javax.swing.JFrame {

    /**
     * Creates new form GUIHineWithLog
     */

    private String rol;
    private long idUser;
    public GUIHomeWithLog(Long idUser,String rol) {
        initComponents();
        this.rol = rol;
        this.idUser = idUser;
        ControllerHomeWithLog controller = new ControllerHomeWithLog(this);
    }

    public long getidUser() {
        return idUser;
    }

    public JButton getjBtnAsignar() {
        return jBtnAsignar;
    }

    public JButton getjBtnCoordiSoli() {
        return jBtnCoordiSoli;
    }

    public JButton getjBtnGetOut() {
        return jBtnGetOut;
    }

    public JButton getjBtnLoginU() {
        return jBtnLoginU;
    }

    public JButton getjBtnMyPubli() {
        return jBtnMyPubli;
    }

    public JButton getjBtnNewPubli() {
        return jBtnNewPubli;
    }

    public JButton getjBtnSearch() {
        return jBtnSearch;
    }

    public JButton getjBtnSolicitudes() {
        return jBtnSolicitudes;
    }

    public JButton getjBtnUsersSistema() {
        return jBtnUsersSistema;
    }

    public JButton getjButtonQuitF() {
        return jButtonQuitF;
    }
    
    public String getRol() {
        return rol;
    }

    public long getIdUser() {
        return idUser;
    }
    
    public JPanel getJPoptions(){
        return jPOptions;
    }


    public JLabel getLbLogin() {
        return lbLogin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPHead = new javax.swing.JPanel();
        lbTitleProyect = new java.awt.Label();
        jPOpcLogin = new javax.swing.JPanel();
        jBtnLoginU = new javax.swing.JButton();
        lbLogin = new javax.swing.JLabel();
        jPSearchBar = new javax.swing.JPanel();
        jCBSelecFilter = new javax.swing.JComboBox<>();
        jFieldSearchProyect = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jButtonQuitF = new javax.swing.JButton();
        jSeparator = new javax.swing.JSeparator();
        jPContent = new javax.swing.JPanel();
        jPOptions = new javax.swing.JPanel();
        jPOpcionCompany = new javax.swing.JPanel();
        jBtnNewPubli = new javax.swing.JButton();
        jBtnMyPubli = new javax.swing.JButton();
        jPOpcionCoordi = new javax.swing.JPanel();
        jBtnSolicitudes = new javax.swing.JButton();
        jBtnAsignar = new javax.swing.JButton();
        jPOpcionStudent = new javax.swing.JPanel();
        jPOpcionAdmin = new javax.swing.JPanel();
        jBtnUsersSistema = new javax.swing.JButton();
        jBtnCoordiSoli = new javax.swing.JButton();
        jPPublis = new javax.swing.JPanel();
        jLTitleProjects = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjects = new javax.swing.JTable();
        jPSideMenu = new javax.swing.JPanel();
        jLTittleMenu = new javax.swing.JLabel();
        jBtnGetOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setLayout(new javax.swing.BoxLayout(jPHead, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbTitleProyect.setText("Sistema gestor de proyectos academicos");
        jPHead.add(lbTitleProyect);

        jPOpcLogin.setBackground(new java.awt.Color(236, 230, 240));
        jPOpcLogin.setLayout(new java.awt.GridLayout(2, 2, 10, 0));

        jBtnLoginU.setBackground(new java.awt.Color(236, 230, 240));
        jBtnLoginU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LoginUser2.png"))); // NOI18N
        jBtnLoginU.setBorder(null);
        jBtnLoginU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnLoginU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLoginU.setIconTextGap(5);
        jBtnLoginU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnLoginU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcLogin.add(jBtnLoginU);

        lbLogin.setBackground(new java.awt.Color(101, 85, 153));
        lbLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(255, 255, 255));
        lbLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogin.setText("Mi User");
        lbLogin.setOpaque(true);
        jPOpcLogin.add(lbLogin);

        jPHead.add(jPOpcLogin);

        jPSearchBar.setBackground(new java.awt.Color(236, 230, 240));
        jPSearchBar.setLayout(new java.awt.GridBagLayout());

        jCBSelecFilter.setBackground(new java.awt.Color(236, 230, 240));
        jCBSelecFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Nombre", "Por Compañia", "Por Estudiante" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPSearchBar.add(jCBSelecFilter, gridBagConstraints);

        jFieldSearchProyect.setBackground(new java.awt.Color(236, 230, 240));
        jFieldSearchProyect.setText("Ingrese un proyecto a buscar...");
        jFieldSearchProyect.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jFieldSearchProyect.setMinimumSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        jPSearchBar.add(jFieldSearchProyect, gridBagConstraints);

        jBtnSearch.setBackground(new java.awt.Color(236, 230, 240));
        jBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/search.png"))); // NOI18N
        jBtnSearch.setBorderPainted(false);
        jPSearchBar.add(jBtnSearch, new java.awt.GridBagConstraints());

        jButtonQuitF.setText("Quitar filtro");
        jPSearchBar.add(jButtonQuitF, new java.awt.GridBagConstraints());
        jButtonQuitF.setVisible(false);

        jSeparator.setBackground(new java.awt.Color(236, 230, 240));
        jSeparator.setForeground(new java.awt.Color(204, 204, 204));

        jPContent.setBackground(new java.awt.Color(236, 230, 240));

        jPOptions.setBackground(new java.awt.Color(236, 230, 240));
        jPOptions.setLayout(new java.awt.CardLayout());

        jPOpcionCompany.setBackground(new java.awt.Color(236, 230, 240));

        jBtnNewPubli.setBackground(new java.awt.Color(101, 85, 153));
        jBtnNewPubli.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnNewPubli.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNewPubli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/newPubli.png"))); // NOI18N
        jBtnNewPubli.setText("Nueva publicación");
        jBtnNewPubli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnNewPubli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcionCompany.add(jBtnNewPubli);

        jBtnMyPubli.setBackground(new java.awt.Color(101, 85, 153));
        jBtnMyPubli.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnMyPubli.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMyPubli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MyPubli.png"))); // NOI18N
        jBtnMyPubli.setText("Mis publicaciones");
        jBtnMyPubli.setToolTipText("");
        jBtnMyPubli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnMyPubli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcionCompany.add(jBtnMyPubli);

        jPOptions.add(jPOpcionCompany, "Empresa");

        jPOpcionCoordi.setBackground(new java.awt.Color(236, 230, 240));

        jBtnSolicitudes.setBackground(new java.awt.Color(101, 85, 153));
        jBtnSolicitudes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnSolicitudes.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSolicitudes.setText("Solicitudes");
        jBtnSolicitudes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnSolicitudes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBtnAsignar.setBackground(new java.awt.Color(101, 85, 153));
        jBtnAsignar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnAsignar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAsignar.setText("Asignar Proyecto");
        jBtnAsignar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAsignar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPOpcionCoordiLayout = new javax.swing.GroupLayout(jPOpcionCoordi);
        jPOpcionCoordi.setLayout(jPOpcionCoordiLayout);
        jPOpcionCoordiLayout.setHorizontalGroup(
            jPOpcionCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionCoordiLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jBtnSolicitudes)
                .addGap(54, 54, 54)
                .addComponent(jBtnAsignar)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPOpcionCoordiLayout.setVerticalGroup(
            jPOpcionCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionCoordiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPOpcionCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPOptions.add(jPOpcionCoordi, "Coordinador");

        jPOpcionStudent.setBackground(new java.awt.Color(236, 230, 240));

        javax.swing.GroupLayout jPOpcionStudentLayout = new javax.swing.GroupLayout(jPOpcionStudent);
        jPOpcionStudent.setLayout(jPOpcionStudentLayout);
        jPOpcionStudentLayout.setHorizontalGroup(
            jPOpcionStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        jPOpcionStudentLayout.setVerticalGroup(
            jPOpcionStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPOptions.add(jPOpcionStudent, "Estudiante");

        jPOpcionAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jPOpcionAdmin.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 30));

        jBtnUsersSistema.setText("VER USUARIOS EN EL SISTEMA");
        jPOpcionAdmin.add(jBtnUsersSistema);

        jBtnCoordiSoli.setText("GESTION DE COORDINADORES");
        jPOpcionAdmin.add(jBtnCoordiSoli);

        jPOptions.add(jPOpcionAdmin, "Admin");

        jPPublis.setBackground(new java.awt.Color(236, 230, 240));
        jPPublis.setLayout(new javax.swing.BoxLayout(jPPublis, javax.swing.BoxLayout.Y_AXIS));

        jLTitleProjects.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLTitleProjects.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitleProjects.setText("Proyectos disponibles");
        jPPublis.add(jLTitleProjects);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProjects);

        jPPublis.add(jScrollPane1);

        javax.swing.GroupLayout jPContentLayout = new javax.swing.GroupLayout(jPContent);
        jPContent.setLayout(jPContentLayout);
        jPContentLayout.setHorizontalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPPublis, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPContentLayout.setVerticalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addComponent(jPOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPPublis, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
        );

        jPSideMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPSideMenu.setLayout(new java.awt.GridBagLayout());

        jLTittleMenu.setBackground(new java.awt.Color(0, 0, 0));
        jLTittleMenu.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLTittleMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleMenu.setText("Menú");
        jLTittleMenu.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPSideMenu.add(jLTittleMenu, gridBagConstraints);

        jBtnGetOut.setBackground(new java.awt.Color(101, 85, 153));
        jBtnGetOut.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jBtnGetOut.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGetOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Get out.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        jPSideMenu.add(jBtnGetOut, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPSearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPSideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPSideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAsignar;
    private javax.swing.JButton jBtnCoordiSoli;
    private javax.swing.JButton jBtnGetOut;
    private javax.swing.JButton jBtnLoginU;
    private javax.swing.JButton jBtnMyPubli;
    private javax.swing.JButton jBtnNewPubli;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jBtnSolicitudes;
    private javax.swing.JButton jBtnUsersSistema;
    private javax.swing.JButton jButtonQuitF;
    private javax.swing.JComboBox<String> jCBSelecFilter;
    private javax.swing.JTextField jFieldSearchProyect;
    private javax.swing.JLabel jLTitleProjects;
    private javax.swing.JLabel jLTittleMenu;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPOpcLogin;
    private javax.swing.JPanel jPOpcionAdmin;
    private javax.swing.JPanel jPOpcionCompany;
    private javax.swing.JPanel jPOpcionCoordi;
    private javax.swing.JPanel jPOpcionStudent;
    private javax.swing.JPanel jPOptions;
    private javax.swing.JPanel jPPublis;
    private javax.swing.JPanel jPSearchBar;
    private javax.swing.JPanel jPSideMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JTable jTableProjects;
    private javax.swing.JLabel lbLogin;
    private java.awt.Label lbTitleProyect;
    // End of variables declaration//GEN-END:variables
}
