/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI;

import co.edu.unicauca.academicproject.GUI.controller.Login.ControllerLogin;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUILogin extends javax.swing.JFrame {

    /**
     * Creates new form GUILogin
     */
    public GUILogin() {
        initComponents();
        ControllerLogin controller = new ControllerLogin(this);
    }

    public JButton getjBtnBackHomeWithLogin() {
        return jBtnBackHomeWithLogin;
    }

    public JButton getjBtnNewUser() {
        return jBtnNewUser;
    }
    
    public JComboBox getCBRol(){
        return jCBRol;
    }
    
    public JButton getBtnLogin(){
        return jBtnPassUser;
    }

    public JTextField getFieldUserName(){
        return jFieldUserName;
    }

    public JPasswordField getPasswordUser(){
        return jPasswordUser;
    }

    public JCheckBox getCheckSeePass(){
        return jCheckSeePass;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPButtom = new javax.swing.JPanel();
        jBtnBackHomeWithLogin = new javax.swing.JButton();
        jPContent = new javax.swing.JPanel();
        jPFormUser = new javax.swing.JPanel();
        jLUser = new javax.swing.JLabel();
        jFieldUserName = new javax.swing.JTextField();
        jLPassWord = new javax.swing.JLabel();
        jPasswordUser = new javax.swing.JPasswordField();
        jBtnPassUser = new javax.swing.JButton();
        jBtnPasswordForget = new javax.swing.JButton();
        jBtnNewUser = new javax.swing.JButton();
        jPRol = new javax.swing.JPanel();
        jLTitleRol = new javax.swing.JLabel();
        jCBRol = new javax.swing.JComboBox<>();
        jCheckSeePass = new javax.swing.JCheckBox();
        jPHead = new javax.swing.JPanel();
        iconLoginUser = new javax.swing.JLabel();
        jLTitittleLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPButtom.setBackground(new java.awt.Color(236, 230, 240));
        jPButtom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jBtnBackHomeWithLogin.setBackground(new java.awt.Color(236, 230, 240));
        jBtnBackHomeWithLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jBtnBackHomeWithLogin.setBorderPainted(false);
        jPButtom.add(jBtnBackHomeWithLogin);

        jPContent.setBackground(new java.awt.Color(236, 230, 240));

        jPFormUser.setBackground(new java.awt.Color(255, 255, 255));
        jPFormUser.setLayout(new java.awt.GridBagLayout());

        jLUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLUser.setText("Codigo de usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 10, 10);
        jPFormUser.add(jLUser, gridBagConstraints);

        jFieldUserName.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldUserName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldUserName.setText("104621....");
        jFieldUserName.setMaximumSize(new java.awt.Dimension(100, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        jPFormUser.add(jFieldUserName, gridBagConstraints);

        jLPassWord.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLPassWord.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLPassWord.setText("Clave:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPFormUser.add(jLPassWord, gridBagConstraints);

        jPasswordUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPasswordUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPasswordUser.setText("jPasswordField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 10);
        jPFormUser.add(jPasswordUser, gridBagConstraints);

        jBtnPassUser.setBackground(new java.awt.Color(0, 0, 0));
        jBtnPassUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jBtnPassUser.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPassUser.setText("INGRESAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPFormUser.add(jBtnPassUser, gridBagConstraints);

        jBtnPasswordForget.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jBtnPasswordForget.setText("¿Olvidaste la contraseña?");
        jBtnPasswordForget.setBorderPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPFormUser.add(jBtnPasswordForget, gridBagConstraints);

        jBtnNewUser.setBackground(new java.awt.Color(236, 230, 240));
        jBtnNewUser.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jBtnNewUser.setText("¿No tienes cuenta?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPFormUser.add(jBtnNewUser, gridBagConstraints);

        jPRol.setBackground(new java.awt.Color(255, 255, 255));
        jPRol.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jLTitleRol.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLTitleRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLTitleRol.setText("Soy un:");
        jLTitleRol.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLTitleRol.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPRol.add(jLTitleRol);

        jCBRol.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCBRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Empresa", "Coordinador", "Admin" }));
        jCBRol.setPreferredSize(new java.awt.Dimension(150, 22));
        jPRol.add(jCBRol);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 10);
        jPFormUser.add(jPRol, gridBagConstraints);

        jCheckSeePass.setBackground(new java.awt.Color(255, 255, 255));
        jCheckSeePass.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCheckSeePass.setText("Ver clave");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        jPFormUser.add(jCheckSeePass, gridBagConstraints);

        jPContent.add(jPFormUser);

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setLayout(new java.awt.GridBagLayout());

        iconLoginUser.setBackground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setForeground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LoginUser3.png"))); // NOI18N
        iconLoginUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPHead.add(iconLoginUser, gridBagConstraints);

        jLTitittleLogin.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLTitittleLogin.setText("Inicio de Sesion - Sistema proyectos");
        jLTitittleLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLTitittleLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPHead.add(jLTitittleLogin, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
            .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLoginUser;
    private javax.swing.JButton jBtnBackHomeWithLogin;
    private javax.swing.JButton jBtnNewUser;
    private javax.swing.JButton jBtnPassUser;
    private javax.swing.JButton jBtnPasswordForget;
    private javax.swing.JComboBox<String> jCBRol;
    private javax.swing.JCheckBox jCheckSeePass;
    private javax.swing.JTextField jFieldUserName;
    private javax.swing.JLabel jLPassWord;
    private javax.swing.JLabel jLTitittleLogin;
    private javax.swing.JLabel jLTitleRol;
    private javax.swing.JLabel jLUser;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPFormUser;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPRol;
    private javax.swing.JPasswordField jPasswordUser;
    // End of variables declaration//GEN-END:variables
}
