server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/project/**
        - id: student-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/student/**
        - id: coordinator-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/coordinator/**
        - id: company-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/company/**
        - id: admin-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/admin/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sistema

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
