/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI.admin;

/**
 *
 * @author lopez
 */
public class GUIRequestCoordinator extends javax.swing.JFrame {

    /**
     * Creates new form GUIRequestCoordinator
     */
    public GUIRequestCoordinator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPHead = new javax.swing.JPanel();
        iconLoginUser = new javax.swing.JLabel();
        jLTitittleLogin = new javax.swing.JLabel();
        jPButtom = new javax.swing.JPanel();
        jBtnBackHomeWithLogin = new javax.swing.JButton();
        jPContent = new javax.swing.JPanel();
        jPCoordi = new javax.swing.JPanel();
        jLCoordinator = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHistoryCoordi = new javax.swing.JTable();
        jPCoordiSinEstado = new javax.swing.JPanel();
        jLSolisSinAtender = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSoliCoordi = new javax.swing.JTable();
        jLNombreCoordi = new javax.swing.JLabel();
        jPValidarCoordi = new javax.swing.JPanel();
        jRBtnAceptar = new javax.swing.JRadioButton();
        jRBtnRechazar = new javax.swing.JRadioButton();
        jBtnProcesarSoli = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setLayout(new java.awt.GridBagLayout());

        iconLoginUser.setBackground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setForeground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPHead.add(iconLoginUser, gridBagConstraints);

        jLTitittleLogin.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLTitittleLogin.setText("Solicitudes de coordinadores - Sistema proyectos");
        jLTitittleLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLTitittleLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPHead.add(jLTitittleLogin, gridBagConstraints);

        jPButtom.setBackground(new java.awt.Color(236, 230, 240));
        jPButtom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jBtnBackHomeWithLogin.setBackground(new java.awt.Color(236, 230, 240));
        jBtnBackHomeWithLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jBtnBackHomeWithLogin.setBorderPainted(false);
        jPButtom.add(jBtnBackHomeWithLogin);

        jPContent.setBackground(new java.awt.Color(236, 230, 240));

        jPCoordi.setBackground(new java.awt.Color(255, 255, 255));

        jLCoordinator.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLCoordinator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCoordinator.setText("Historial de solicitudes de coordinarores:");

        jTableHistoryCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableHistoryCoordi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableHistoryCoordi);

        javax.swing.GroupLayout jPCoordiLayout = new javax.swing.GroupLayout(jPCoordi);
        jPCoordi.setLayout(jPCoordiLayout);
        jPCoordiLayout.setHorizontalGroup(
            jPCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCoordiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPCoordiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCoordinator, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPCoordiLayout.setVerticalGroup(
            jPCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLCoordinator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPCoordiSinEstado.setBackground(new java.awt.Color(255, 255, 255));

        jLSolisSinAtender.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLSolisSinAtender.setText("Solicitudes ");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTableSoliCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableSoliCoordi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableSoliCoordi);

        javax.swing.GroupLayout jPCoordiSinEstadoLayout = new javax.swing.GroupLayout(jPCoordiSinEstado);
        jPCoordiSinEstado.setLayout(jPCoordiSinEstadoLayout);
        jPCoordiSinEstadoLayout.setHorizontalGroup(
            jPCoordiSinEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordiSinEstadoLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLSolisSinAtender)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCoordiSinEstadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237))
        );
        jPCoordiSinEstadoLayout.setVerticalGroup(
            jPCoordiSinEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordiSinEstadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLSolisSinAtender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );

        jLNombreCoordi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLNombreCoordi.setText("NOMBRE COORDI");

        jPValidarCoordi.setBackground(new java.awt.Color(255, 255, 255));

        jRBtnAceptar.setBackground(new java.awt.Color(204, 255, 204));
        jRBtnAceptar.setText("Aceptar solicitud");

        jRBtnRechazar.setBackground(new java.awt.Color(255, 153, 153));
        jRBtnRechazar.setText("Rechazar Solicitud");

        jBtnProcesarSoli.setText("ACEPTAR");

        javax.swing.GroupLayout jPValidarCoordiLayout = new javax.swing.GroupLayout(jPValidarCoordi);
        jPValidarCoordi.setLayout(jPValidarCoordiLayout);
        jPValidarCoordiLayout.setHorizontalGroup(
            jPValidarCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPValidarCoordiLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jRBtnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jRBtnRechazar)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPValidarCoordiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnProcesarSoli)
                .addGap(130, 130, 130))
        );
        jPValidarCoordiLayout.setVerticalGroup(
            jPValidarCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPValidarCoordiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPValidarCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBtnAceptar)
                    .addComponent(jRBtnRechazar))
                .addGap(18, 18, 18)
                .addComponent(jBtnProcesarSoli)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPContentLayout = new javax.swing.GroupLayout(jPContent);
        jPContent.setLayout(jPContentLayout);
        jPContentLayout.setHorizontalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPCoordi, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPCoordiSinEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLNombreCoordi))
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jPValidarCoordi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPContentLayout.setVerticalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPCoordi, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addComponent(jPCoordiSinEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLNombreCoordi)
                        .addGap(11, 11, 11)
                        .addComponent(jPValidarCoordi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLoginUser;
    private javax.swing.JButton jBtnBackHomeWithLogin;
    private javax.swing.JButton jBtnProcesarSoli;
    private javax.swing.JLabel jLCoordinator;
    private javax.swing.JLabel jLNombreCoordi;
    private javax.swing.JLabel jLSolisSinAtender;
    private javax.swing.JLabel jLTitittleLogin;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPCoordi;
    private javax.swing.JPanel jPCoordiSinEstado;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPValidarCoordi;
    private javax.swing.JRadioButton jRBtnAceptar;
    private javax.swing.JRadioButton jRBtnRechazar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableHistoryCoordi;
    private javax.swing.JTable jTableSoliCoordi;
    // End of variables declaration//GEN-END:variables
}
