/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI.admin;

/**
 *
 * @author lopez
 */
public class GUIUsers extends javax.swing.JFrame {

    /**
     * Creates new form GUIUsers
     */
    public GUIUsers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPHead = new javax.swing.JPanel();
        iconLoginUser = new javax.swing.JLabel();
        jLTitittleLogin = new javax.swing.JLabel();
        jPButtom = new javax.swing.JPanel();
        jBtnBackHomeWithLogin = new javax.swing.JButton();
        jPContent = new javax.swing.JPanel();
        jPCoordi = new javax.swing.JPanel();
        jLCoordinator = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCoordinator = new javax.swing.JTable();
        jPSudent = new javax.swing.JPanel();
        jLStudent1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jPCompany = new javax.swing.JPanel();
        jLCompany1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCompany = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setLayout(new java.awt.GridBagLayout());

        iconLoginUser.setBackground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setForeground(new java.awt.Color(101, 85, 153));
        iconLoginUser.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPHead.add(iconLoginUser, gridBagConstraints);

        jLTitittleLogin.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLTitittleLogin.setText("Listado usuarios - Sistema proyectos");
        jLTitittleLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLTitittleLogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPHead.add(jLTitittleLogin, gridBagConstraints);

        jPButtom.setBackground(new java.awt.Color(236, 230, 240));
        jPButtom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jBtnBackHomeWithLogin.setBackground(new java.awt.Color(236, 230, 240));
        jBtnBackHomeWithLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        jBtnBackHomeWithLogin.setBorderPainted(false);
        jPButtom.add(jBtnBackHomeWithLogin);

        jPContent.setBackground(new java.awt.Color(236, 230, 240));
        jPContent.setLayout(new javax.swing.BoxLayout(jPContent, javax.swing.BoxLayout.LINE_AXIS));

        jPCoordi.setBackground(new java.awt.Color(255, 255, 255));

        jLCoordinator.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLCoordinator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCoordinator.setText("Coordinadores");

        jTableCoordinator.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableCoordinator.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCoordinator);

        javax.swing.GroupLayout jPCoordiLayout = new javax.swing.GroupLayout(jPCoordi);
        jPCoordi.setLayout(jPCoordiLayout);
        jPCoordiLayout.setHorizontalGroup(
            jPCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCoordiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLCoordinator, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(148, 148, 148))
        );
        jPCoordiLayout.setVerticalGroup(
            jPCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLCoordinator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPContent.add(jPCoordi);

        jPSudent.setBackground(new java.awt.Color(255, 255, 255));

        jLStudent1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLStudent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLStudent1.setText("Estudiantes");

        jTableStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableStudent);

        javax.swing.GroupLayout jPSudentLayout = new javax.swing.GroupLayout(jPSudent);
        jPSudent.setLayout(jPSudentLayout);
        jPSudentLayout.setHorizontalGroup(
            jPSudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPSudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLStudent1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(148, 148, 148))
        );
        jPSudentLayout.setVerticalGroup(
            jPSudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSudentLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLStudent1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPContent.add(jPSudent);

        jPCompany.setBackground(new java.awt.Color(255, 255, 255));

        jLCompany1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLCompany1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCompany1.setText("Empresas");

        jTableCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTableCompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTableCompany);

        javax.swing.GroupLayout jPCompanyLayout = new javax.swing.GroupLayout(jPCompany);
        jPCompany.setLayout(jPCompanyLayout);
        jPCompanyLayout.setHorizontalGroup(
            jPCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCompanyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLCompany1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(148, 148, 148))
        );
        jPCompanyLayout.setVerticalGroup(
            jPCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCompanyLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLCompany1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPContent.add(jPCompany);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLoginUser;
    private javax.swing.JButton jBtnBackHomeWithLogin;
    private javax.swing.JLabel jLCompany1;
    private javax.swing.JLabel jLCoordinator;
    private javax.swing.JLabel jLStudent1;
    private javax.swing.JLabel jLTitittleLogin;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPCompany;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPCoordi;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPSudent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCompany;
    private javax.swing.JTable jTableCoordinator;
    private javax.swing.JTable jTableStudent;
    // End of variables declaration//GEN-END:variables
}
