/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI.company;

import co.edu.unicauca.academicproject.GUI.controller.Project.ControllerNewProject;
import co.edu.unicauca.academicproject.entities.Company;
import co.edu.unicauca.academicproject.entities.Project;
import com.toedter.calendar.JDateChooser;
import com.toedter.components.JSpinField;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUINewProject extends javax.swing.JFrame {

    /**
     * Creates new form GUINewProject
     */

    private final Company company;
    private String token;
    public GUINewProject(Company company,String token) {
        initComponents();
        ControllerNewProject controller = new ControllerNewProject(this);
        this.company = company;
        this.token = token;
    }

    public String getTitleProject() {
        return jFieldTitleProject.getText();
    }

    public String getDescriptionProject() {
        return jTextAreaDescripProject.getText();
    }

   public JButton getjBtnPubliProject() {
        return jBtnPubliProject;
    }

    public Company getCompany() {
        return company;
    }
    
    public String getResumenProject(){
        return jTextAreaResumen.getText();
    }
    
    public String getObjetivos(){
        return jTextAreaObjetivos.getText();
    }
    
    public JSpinField getDuracionMes(){
        return jSpinDuracionMes;
    }
    
    public JDateChooser getFechaProyecto(){
        return jDateChFechaInicio;
    }
    
    public JTextField getPresupuesto(){
        return jFieldPresupuesto;
    }
    
    public JSpinField getAnio(){
        return jYearProyecto;
    }
    
    public JSpinField getTerm(){
        return jSpinTerm;
    }

    public String getToken(){
        return token;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPContent = new javax.swing.JPanel();
        jLTitleProject = new javax.swing.JLabel();
        jFieldTitleProject = new javax.swing.JTextField();
        jLDescriptionProject = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripProject = new javax.swing.JTextArea();
        jBtnPubliProject = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLResumen = new javax.swing.JLabel();
        jTextAreaResumen = new javax.swing.JTextField();
        jLObjetivos = new javax.swing.JLabel();
        jTextAreaObjetivos = new javax.swing.JTextField();
        jLDuracionMeses = new javax.swing.JLabel();
        jLFechaInicioProyecto = new javax.swing.JLabel();
        jDateChFechaInicio = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jYearProyecto = new com.toedter.calendar.JYearChooser();
        jSpinTerm = new com.toedter.components.JSpinField();
        jSpinDuracionMes = new com.toedter.components.JSpinField();
        jFieldPresupuesto = new javax.swing.JTextField();
        jPTitleNewProject = new javax.swing.JPanel();
        jBtnNewPubli = new javax.swing.JButton();
        jPHead = new javax.swing.JPanel();
        lbTitleProyect = new java.awt.Label();
        jPOpcLogin = new javax.swing.JPanel();
        jBtnLoginU = new javax.swing.JButton();
        jPButtom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva publicacion");
        setBackground(new java.awt.Color(15, 32, 65));
        setMinimumSize(new java.awt.Dimension(700, 550));

        jPContent.setBackground(new java.awt.Color(15, 32, 65));
        jPContent.setForeground(new java.awt.Color(255, 255, 255));
        jPContent.setLayout(new java.awt.GridBagLayout());

        jLTitleProject.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLTitleProject.setForeground(new java.awt.Color(255, 255, 255));
        jLTitleProject.setText("Titulo del proyecto:");
        jPContent.add(jLTitleProject, new java.awt.GridBagConstraints());

        jFieldTitleProject.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jFieldTitleProject.setText("Mi proyecto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPContent.add(jFieldTitleProject, gridBagConstraints);

        jLDescriptionProject.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLDescriptionProject.setForeground(new java.awt.Color(255, 255, 255));
        jLDescriptionProject.setText("Descripción del proyecto: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPContent.add(jLDescriptionProject, gridBagConstraints);

        jTextAreaDescripProject.setColumns(20);
        jTextAreaDescripProject.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextAreaDescripProject.setLineWrap(true);
        jTextAreaDescripProject.setRows(5);
        jTextAreaDescripProject.setText("Proyecto enfocado en los sitemas gestores academicos\n");
        jScrollPane1.setViewportView(jTextAreaDescripProject);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPContent.add(jScrollPane1, gridBagConstraints);

        jBtnPubliProject.setBackground(new java.awt.Color(172, 0, 0));
        jBtnPubliProject.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jBtnPubliProject.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPubliProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/publicar.png"))); // NOI18N
        jBtnPubliProject.setText("PUBLICAR ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        jPContent.add(jBtnPubliProject, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Periodo academico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        jPContent.add(jLabel1, gridBagConstraints);

        jLResumen.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLResumen.setForeground(new java.awt.Color(255, 255, 255));
        jLResumen.setText("Resumen:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        jPContent.add(jLResumen, gridBagConstraints);

        jTextAreaResumen.setText("jTextField1");
        jTextAreaResumen.setMaximumSize(new java.awt.Dimension(250, 30));
        jTextAreaResumen.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextAreaResumen.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPContent.add(jTextAreaResumen, gridBagConstraints);

        jLObjetivos.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLObjetivos.setForeground(new java.awt.Color(255, 255, 255));
        jLObjetivos.setText("Objetivos:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 50, 0, 0);
        jPContent.add(jLObjetivos, gridBagConstraints);

        jTextAreaObjetivos.setText("jTextField2");
        jTextAreaObjetivos.setMaximumSize(new java.awt.Dimension(250, 30));
        jTextAreaObjetivos.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextAreaObjetivos.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPContent.add(jTextAreaObjetivos, gridBagConstraints);

        jLDuracionMeses.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLDuracionMeses.setForeground(new java.awt.Color(255, 255, 255));
        jLDuracionMeses.setText("Duracion del proyecto(meses):");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 0);
        jPContent.add(jLDuracionMeses, gridBagConstraints);

        jLFechaInicioProyecto.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLFechaInicioProyecto.setForeground(new java.awt.Color(255, 255, 255));
        jLFechaInicioProyecto.setText("Fecha inicio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        jPContent.add(jLFechaInicioProyecto, gridBagConstraints);

        jDateChFechaInicio.setDateFormatString("y-MM-d");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPContent.add(jDateChFechaInicio, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Presupuesto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPContent.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        jPContent.add(jYearProyecto, gridBagConstraints);

        jSpinTerm.setMaximum(2);
        jSpinTerm.setMinimum(1);
        jSpinTerm.setValue(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(30, 100, 0, 0);
        jPContent.add(jSpinTerm, gridBagConstraints);

        jSpinDuracionMes.setMaximum(12);
        jSpinDuracionMes.setMinimum(1);
        jSpinDuracionMes.setValue(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPContent.add(jSpinDuracionMes, gridBagConstraints);

        jFieldPresupuesto.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPContent.add(jFieldPresupuesto, gridBagConstraints);

        jPTitleNewProject.setBackground(new java.awt.Color(15, 32, 65));
        jPTitleNewProject.setForeground(new java.awt.Color(255, 255, 255));

        jBtnNewPubli.setBackground(new java.awt.Color(172, 0, 0));
        jBtnNewPubli.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnNewPubli.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNewPubli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/newPubli.png"))); // NOI18N
        jBtnNewPubli.setText("Nueva publicación");
        jBtnNewPubli.setBorderPainted(false);
        jBtnNewPubli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnNewPubli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPTitleNewProject.add(jBtnNewPubli);

        jPHead.setBackground(new java.awt.Color(15, 32, 65));
        jPHead.setLayout(new javax.swing.BoxLayout(jPHead, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect.setBackground(new java.awt.Color(15, 32, 65));
        lbTitleProyect.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbTitleProyect.setForeground(new java.awt.Color(255, 255, 255));
        lbTitleProyect.setText("Sistema gestor de proyectos academicos");
        jPHead.add(lbTitleProyect);

        jPOpcLogin.setBackground(new java.awt.Color(236, 230, 240));
        jPOpcLogin.setLayout(new java.awt.GridLayout(1, 1, 1, 0));

        jBtnLoginU.setBackground(new java.awt.Color(172, 0, 0));
        jBtnLoginU.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnLoginU.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLoginU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/usuario.png"))); // NOI18N
        jBtnLoginU.setText("My User");
        jBtnLoginU.setBorder(null);
        jBtnLoginU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnLoginU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLoginU.setIconTextGap(5);
        jBtnLoginU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnLoginU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcLogin.add(jBtnLoginU);

        jPHead.add(jPOpcLogin);

        jPButtom.setBackground(new java.awt.Color(15, 32, 65));

        javax.swing.GroupLayout jPButtomLayout = new javax.swing.GroupLayout(jPButtom);
        jPButtom.setLayout(jPButtomLayout);
        jPButtomLayout.setHorizontalGroup(
            jPButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1066, Short.MAX_VALUE)
        );
        jPButtomLayout.setVerticalGroup(
            jPButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPTitleNewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPTitleNewProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 48, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(495, 495, 495)
                    .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLoginU;
    private javax.swing.JButton jBtnNewPubli;
    private javax.swing.JButton jBtnPubliProject;
    private com.toedter.calendar.JDateChooser jDateChFechaInicio;
    private javax.swing.JTextField jFieldPresupuesto;
    private javax.swing.JTextField jFieldTitleProject;
    private javax.swing.JLabel jLDescriptionProject;
    private javax.swing.JLabel jLDuracionMeses;
    private javax.swing.JLabel jLFechaInicioProyecto;
    private javax.swing.JLabel jLObjetivos;
    private javax.swing.JLabel jLResumen;
    private javax.swing.JLabel jLTitleProject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPOpcLogin;
    private javax.swing.JPanel jPTitleNewProject;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinField jSpinDuracionMes;
    private com.toedter.components.JSpinField jSpinTerm;
    private javax.swing.JTextArea jTextAreaDescripProject;
    private javax.swing.JTextField jTextAreaObjetivos;
    private javax.swing.JTextField jTextAreaResumen;
    private com.toedter.calendar.JYearChooser jYearProyecto;
    private java.awt.Label lbTitleProyect;
    // End of variables declaration//GEN-END:variables
}
