/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI.coordinator;

import co.edu.unicauca.academicproject.GUI.controller.coordinator.controllerAssigment;
import co.edu.unicauca.academicproject.entities.observer.Observer;
import co.edu.unicauca.academicproject.entities.observer.Sujeto;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUIAssigment extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form GUIAssigment
     */
    private String token;
    public GUIAssigment(String token, Sujeto sujeto) {
        initComponents();
        sujeto.agregarObservador(this);
        this.token = token;
        controllerAssigment vista = new controllerAssigment(this,sujeto);
    }

    public String getToken(){
        return token;
    }
    
    public JButton getjBtnAtras() {
        return jBtnAtras;
    }


    public JButton getjBtnSaveProject() {
        return jBtnSaveProject;
    }

    public JTable getjTableProjects() {
        return jTableProjects;
    }

    public JTable getjTableStudent() {
        return jTableStudent;
    }

    public JLabel getjLStudent() {
        return jLStudent;
    }

    public JLabel getjLabelNameProject() {
        return jLabelNameProject;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPHead = new javax.swing.JPanel();
        lbTitleProyect = new java.awt.Label();
        jPContent = new javax.swing.JPanel();
        jPStudent = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPProjects = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjects = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLtitleProyecto = new javax.swing.JLabel();
        jBtnSaveProject = new javax.swing.JButton();
        jLabelNameProject = new javax.swing.JLabel();
        jLStudent = new javax.swing.JLabel();
        jBtnAtras = new javax.swing.JButton();
        jPTittleNewUser = new javax.swing.JPanel();
        jLTittleNewUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion nueva asignacion");
        setMinimumSize(new java.awt.Dimension(1080, 970));

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setLayout(new javax.swing.BoxLayout(jPHead, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect.setAlignment(java.awt.Label.CENTER);
        lbTitleProyect.setBackground(new java.awt.Color(12, 32, 65));
        lbTitleProyect.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lbTitleProyect.setForeground(new java.awt.Color(255, 255, 255));
        lbTitleProyect.setText("Sistema gestor de proyectos academicos");
        jPHead.add(lbTitleProyect);

        jPContent.setBackground(new java.awt.Color(12, 32, 65));
        jPContent.setForeground(new java.awt.Color(255, 255, 255));

        jPStudent.setBackground(new java.awt.Color(15, 32, 65));

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableStudent);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione un estudiante");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Estudiante seleccionado:");

        javax.swing.GroupLayout jPStudentLayout = new javax.swing.GroupLayout(jPStudent);
        jPStudent.setLayout(jPStudentLayout);
        jPStudentLayout.setHorizontalGroup(
            jPStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPStudentLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPStudentLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(24, 24, 24))
        );
        jPStudentLayout.setVerticalGroup(
            jPStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPStudentLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(26, 26, 26))
        );

        jPProjects.setBackground(new java.awt.Color(15, 32, 65));

        jTableProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProjects);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione un proyecto");

        jLtitleProyecto.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLtitleProyecto.setForeground(new java.awt.Color(255, 255, 255));
        jLtitleProyecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtitleProyecto.setText("Proyecto seleccionado:");

        javax.swing.GroupLayout jPProjectsLayout = new javax.swing.GroupLayout(jPProjects);
        jPProjects.setLayout(jPProjectsLayout);
        jPProjectsLayout.setHorizontalGroup(
            jPProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPProjectsLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLtitleProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );
        jPProjectsLayout.setVerticalGroup(
            jPProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPProjectsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLtitleProyecto)
                .addGap(23, 23, 23))
        );

        jBtnSaveProject.setBackground(new java.awt.Color(153, 255, 153));
        jBtnSaveProject.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jBtnSaveProject.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSaveProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/cheque.png"))); // NOI18N
        jBtnSaveProject.setText("ASIGNAR");
        jBtnSaveProject.setToolTipText("");
        jBtnSaveProject.setBorderPainted(false);

        jLabelNameProject.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabelNameProject.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNameProject.setText("Seleccione un proyecto");

        jLStudent.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLStudent.setForeground(new java.awt.Color(255, 255, 255));
        jLStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLStudent.setText("Seleccione un estudiante");

        jBtnAtras.setBackground(new java.awt.Color(15, 32, 65));
        jBtnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/anterior (1).png"))); // NOI18N
        jBtnAtras.setBorderPainted(false);

        javax.swing.GroupLayout jPContentLayout = new javax.swing.GroupLayout(jPContent);
        jPContent.setLayout(jPContentLayout);
        jPContentLayout.setHorizontalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPContentLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelNameProject, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPContentLayout.createSequentialGroup()
                        .addComponent(jPProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnSaveProject, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(419, 419, 419))
        );
        jPContentLayout.setVerticalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPContentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameProject)
                    .addComponent(jLStudent))
                .addGap(55, 55, 55)
                .addComponent(jBtnSaveProject, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jBtnAtras)
                .addGap(22, 22, 22))
        );

        jPTittleNewUser.setBackground(new java.awt.Color(172, 0, 0));
        jPTittleNewUser.setForeground(new java.awt.Color(255, 255, 255));

        jLTittleNewUser.setBackground(new java.awt.Color(172, 0, 0));
        jLTittleNewUser.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLTittleNewUser.setForeground(new java.awt.Color(255, 255, 255));
        jLTittleNewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleNewUser.setText("Nueva asignación");
        jLTittleNewUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPTittleNewUserLayout = new javax.swing.GroupLayout(jPTittleNewUser);
        jPTittleNewUser.setLayout(jPTittleNewUserLayout);
        jPTittleNewUserLayout.setHorizontalGroup(
            jPTittleNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTittleNewUserLayout.createSequentialGroup()
                .addComponent(jLTittleNewUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPTittleNewUserLayout.setVerticalGroup(
            jPTittleNewUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTittleNewUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTittleNewUser)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTittleNewUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPHead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPTittleNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAtras;
    private javax.swing.JButton jBtnSaveProject;
    private javax.swing.JLabel jLStudent;
    private javax.swing.JLabel jLTittleNewUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelNameProject;
    private javax.swing.JLabel jLtitleProyecto;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPProjects;
    private javax.swing.JPanel jPStudent;
    private javax.swing.JPanel jPTittleNewUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProjects;
    private javax.swing.JTable jTableStudent;
    private java.awt.Label lbTitleProyect;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(String mensaje) {
        System.out.println("Actualizando desde GUI assigment" + mensaje);
    }
}
