/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI.coordinator;

import co.edu.unicauca.academicproject.GUI.controller.coordinator.controllerminiRequest;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUIminiRequest extends javax.swing.JPanel {

    /**
     * Creates new form GUIminiRequest
     */
    private String tituloProyecto,nombreProyecto,estadoProyecto;

    public GUIminiRequest(String tituloProyecto,String nombreEmpresa,String estado) {
        initComponents();
        this.tituloProyecto=tituloProyecto;
        this.nombreProyecto=nombreEmpresa;
        this.estadoProyecto=estado;
        controllerminiRequest controller = new controllerminiRequest(this);
    }

    public String getTituloProyecto() {
        return tituloProyecto;
    }

    public String getNombreProyecto() {
        return nombreProyecto;
    }

    public String getEstadoProyecto() {
        return estadoProyecto;
    }

    public void setjLTituloProyecto(String jLTituloProyecto) {
        this.jLTituloProyecto.setText(jLTituloProyecto);
    }



    public void setjLNombreEmpresa(String jLNombreEmpresa) {
        this.jLNombreEmpresa.setText(jLNombreEmpresa);
    }

    public void setjLEstadoProyecto(String jLEstadoProyecto) {
        this.jLEstadoProyecto.setText(jLEstadoProyecto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTituloProyecto = new javax.swing.JLabel();
        jLTEstudiante = new javax.swing.JLabel();
        jLTEmpresa = new javax.swing.JLabel();
        jLTEstado = new javax.swing.JLabel();
        jLEstudiante = new javax.swing.JLabel();
        jLNombreEmpresa = new javax.swing.JLabel();
        jLEstadoProyecto = new javax.swing.JLabel();

        jLTituloProyecto.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLTituloProyecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTituloProyecto.setText("TITULO PROYECTO");

        jLTEstudiante.setText("Estudiante:");

        jLTEmpresa.setText("Empresa:");

        jLTEstado.setText("Estado:");

        jLEstudiante.setText("Pepito perez");

        jLNombreEmpresa.setText("Lacteos Cauca");

        jLEstadoProyecto.setText("Receibed");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLTituloProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLTEstudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTEmpresa)
                            .addComponent(jLTEstado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLEstadoProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTituloProyecto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTEstudiante)
                    .addComponent(jLEstudiante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTEmpresa)
                    .addComponent(jLNombreEmpresa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTEstado)
                    .addComponent(jLEstadoProyecto))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLEstadoProyecto;
    private javax.swing.JLabel jLEstudiante;
    private javax.swing.JLabel jLNombreEmpresa;
    private javax.swing.JLabel jLTEmpresa;
    private javax.swing.JLabel jLTEstado;
    private javax.swing.JLabel jLTEstudiante;
    private javax.swing.JLabel jLTituloProyecto;
    // End of variables declaration//GEN-END:variables
}
