/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI.coordinator;

import co.edu.unicauca.academicproject.GUI.controller.Project.ControllerNewProject;
import co.edu.unicauca.academicproject.GUI.controller.coordinator.controllerStatistics;
import co.edu.unicauca.academicproject.entities.Company;
import co.edu.unicauca.academicproject.entities.Project;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JYearChooser;
import com.toedter.components.JSpinField;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUIStatistics extends javax.swing.JFrame {

    /**
     * Creates new form GUINewProject
     */

    private String token;
    public GUIStatistics(String token) {
        initComponents();
        controllerStatistics controller = new controllerStatistics(this);
        this.token = token;
    }


    public String getToken(){
        return token;
    }

    public JButton getJBtnFiltrar() {
        return JBtnFiltrar;
    }

    public JYearChooser getjYear() {
        return jYear;
    }

    public JSpinField getjSpinPeriodo() {
        return jSpinPeriodo;
    }

    public JRadioButton getjRbtnGraficoPastel() {
        return jRbtnGraficoPastel;
    }

    public JRadioButton getjRbtnGraficoBarra() {
        return jRbtnGraficoBarra;
    }

    public ButtonGroup getButtonGroupGrafico() {
        return buttonGroupGrafico;
    }

    public JPanel getjPGraficos() {
        return jPGraficos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGrafico = new javax.swing.ButtonGroup();
        jPContent = new javax.swing.JPanel();
        jPGraficos = new javax.swing.JPanel();
        jLDatos = new javax.swing.JLabel();
        jPDatosGraficos = new javax.swing.JPanel();
        jYear = new com.toedter.calendar.JYearChooser();
        jSpinPeriodo = new com.toedter.components.JSpinField();
        JBtnFiltrar = new javax.swing.JButton();
        jRbtnGraficoBarra = new javax.swing.JRadioButton();
        jRbtnGraficoPastel = new javax.swing.JRadioButton();
        jPTitleNewProject = new javax.swing.JPanel();
        jBtnEstadistica = new javax.swing.JButton();
        jPHead = new javax.swing.JPanel();
        lbTitleProyect = new java.awt.Label();
        jPOpcLogin = new javax.swing.JPanel();
        jBtnLoginU = new javax.swing.JButton();
        jPButtom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estadisticas");
        setBackground(new java.awt.Color(15, 32, 65));
        setMinimumSize(new java.awt.Dimension(700, 550));

        jPContent.setBackground(new java.awt.Color(15, 32, 65));
        jPContent.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPGraficosLayout = new javax.swing.GroupLayout(jPGraficos);
        jPGraficos.setLayout(jPGraficosLayout);
        jPGraficosLayout.setHorizontalGroup(
            jPGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1369, Short.MAX_VALUE)
        );
        jPGraficosLayout.setVerticalGroup(
            jPGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );

        jLDatos.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLDatos.setForeground(new java.awt.Color(255, 255, 255));
        jLDatos.setText("Datos para estadísticas:");

        jPDatosGraficos.setLayout(new java.awt.GridLayout(1, 0, 10, 40));
        jPDatosGraficos.add(jYear);

        jSpinPeriodo.setMaximum(2);
        jSpinPeriodo.setMinimum(1);
        jSpinPeriodo.setValue(1);
        jPDatosGraficos.add(jSpinPeriodo);

        JBtnFiltrar.setText("Filtrar");

        jRbtnGraficoBarra.setBackground(new java.awt.Color(15, 32, 65));
        buttonGroupGrafico.add(jRbtnGraficoBarra);
        jRbtnGraficoBarra.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jRbtnGraficoBarra.setForeground(new java.awt.Color(255, 255, 255));
        jRbtnGraficoBarra.setText("Gráfico barra");

        jRbtnGraficoPastel.setBackground(new java.awt.Color(15, 32, 65));
        buttonGroupGrafico.add(jRbtnGraficoPastel);
        jRbtnGraficoPastel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jRbtnGraficoPastel.setForeground(new java.awt.Color(255, 255, 255));
        jRbtnGraficoPastel.setText("Gráfico pastel");

        javax.swing.GroupLayout jPContentLayout = new javax.swing.GroupLayout(jPContent);
        jPContent.setLayout(jPContentLayout);
        jPContentLayout.setHorizontalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPContentLayout.createSequentialGroup()
                                .addComponent(jLDatos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPDatosGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRbtnGraficoPastel)
                                .addGap(24, 24, 24)
                                .addComponent(JBtnFiltrar))))
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jRbtnGraficoBarra)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPContentLayout.setVerticalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPGraficos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addComponent(JBtnFiltrar)
                        .addGap(31, 31, 31))
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addComponent(jRbtnGraficoBarra)
                        .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPContentLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPDatosGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLDatos)))
                            .addGroup(jPContentLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRbtnGraficoPastel)))
                        .addGap(22, 22, 22))))
        );

        jPTitleNewProject.setBackground(new java.awt.Color(15, 32, 65));
        jPTitleNewProject.setForeground(new java.awt.Color(255, 255, 255));

        jBtnEstadistica.setBackground(new java.awt.Color(172, 0, 0));
        jBtnEstadistica.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnEstadistica.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEstadistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/estadisticasBig.png"))); // NOI18N
        jBtnEstadistica.setText("Estadisticas");
        jBtnEstadistica.setBorderPainted(false);
        jBtnEstadistica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnEstadistica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPTitleNewProject.add(jBtnEstadistica);

        jPHead.setBackground(new java.awt.Color(15, 32, 65));
        jPHead.setLayout(new javax.swing.BoxLayout(jPHead, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect.setBackground(new java.awt.Color(15, 32, 65));
        lbTitleProyect.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbTitleProyect.setForeground(new java.awt.Color(255, 255, 255));
        lbTitleProyect.setText("Sistema gestor de proyectos academicos");
        jPHead.add(lbTitleProyect);

        jPOpcLogin.setBackground(new java.awt.Color(236, 230, 240));
        jPOpcLogin.setLayout(new java.awt.GridLayout(1, 1, 1, 0));

        jBtnLoginU.setBackground(new java.awt.Color(172, 0, 0));
        jBtnLoginU.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnLoginU.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLoginU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/usuario.png"))); // NOI18N
        jBtnLoginU.setText("My User");
        jBtnLoginU.setBorder(null);
        jBtnLoginU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnLoginU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLoginU.setIconTextGap(5);
        jBtnLoginU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnLoginU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcLogin.add(jBtnLoginU);

        jPHead.add(jPOpcLogin);

        jPButtom.setBackground(new java.awt.Color(15, 32, 65));

        javax.swing.GroupLayout jPButtomLayout = new javax.swing.GroupLayout(jPButtom);
        jPButtom.setLayout(jPButtomLayout);
        jPButtomLayout.setHorizontalGroup(
            jPButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1395, Short.MAX_VALUE)
        );
        jPButtomLayout.setVerticalGroup(
            jPButtomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPTitleNewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPTitleNewProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(699, 699, 699)
                    .addComponent(jPButtom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnFiltrar;
    private javax.swing.ButtonGroup buttonGroupGrafico;
    private javax.swing.JButton jBtnEstadistica;
    private javax.swing.JButton jBtnLoginU;
    private javax.swing.JLabel jLDatos;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPDatosGraficos;
    private javax.swing.JPanel jPGraficos;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPOpcLogin;
    private javax.swing.JPanel jPTitleNewProject;
    private javax.swing.JRadioButton jRbtnGraficoBarra;
    private javax.swing.JRadioButton jRbtnGraficoPastel;
    private com.toedter.components.JSpinField jSpinPeriodo;
    private com.toedter.calendar.JYearChooser jYear;
    private java.awt.Label lbTitleProyect;
    // End of variables declaration//GEN-END:variables
}
