/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI.coordinator;

import co.edu.unicauca.academicproject.GUI.controller.Project.ControllerNewProject;
import co.edu.unicauca.academicproject.GUI.controller.coordinator.controllerStatistics;
import co.edu.unicauca.academicproject.entities.Company;
import co.edu.unicauca.academicproject.entities.Project;
import co.edu.unicauca.academicproject.entities.observer.Observer;
import co.edu.unicauca.academicproject.entities.observer.Sujeto;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JYearChooser;
import com.toedter.components.JSpinField;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUIStatistics extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form GUINewProject
     */

    private String token;
    public GUIStatistics(String token, Sujeto sujeto) {
        initComponents();
        sujeto.agregarObservador(this);
        controllerStatistics controller = new controllerStatistics(this,sujeto);
        this.token = token;
    }


    public String getToken(){
        return token;
    }

    public JButton getJBtnFiltrar() {
        return JBtnFiltrar;
    }

    public JYearChooser getjYear() {
        return jYear;
    }

    public JSpinField getjSpinPeriodo() {
        return jSpinPeriodo;
    }

    public JRadioButton getjRbtnGraficoPastel() {
        return jRbtnGraficoPastel;
    }

    public JRadioButton getjRbtnGraficoBarra() {
        return jRbtnGraficoBarra;
    }

    public ButtonGroup getButtonGroupGrafico() {
        return buttonGroupGrafico;
    }

    public JPanel getjPGraficos() {
        return jPGraficos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGrafico = new javax.swing.ButtonGroup();
        jPContent = new javax.swing.JPanel();
        jPGraficos = new javax.swing.JPanel();
        jLDatos = new javax.swing.JLabel();
        jPDatosGraficos = new javax.swing.JPanel();
        jYear = new com.toedter.calendar.JYearChooser();
        jSpinPeriodo = new com.toedter.components.JSpinField();
        JBtnFiltrar = new javax.swing.JButton();
        jPOpcionGrafi = new javax.swing.JPanel();
        jRbtnGraficoBarra = new javax.swing.JRadioButton();
        jRbtnGraficoPastel = new javax.swing.JRadioButton();
        jPTitleNewProject = new javax.swing.JPanel();
        jBtnEstadistica = new javax.swing.JButton();
        jPHead = new javax.swing.JPanel();
        lbTitleProyect = new java.awt.Label();
        jPOpcLogin = new javax.swing.JPanel();
        jBtnLoginU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estadisticas");
        setBackground(new java.awt.Color(15, 32, 65));
        setMinimumSize(new java.awt.Dimension(700, 550));

        jPContent.setBackground(new java.awt.Color(15, 32, 65));
        jPContent.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPGraficosLayout = new javax.swing.GroupLayout(jPGraficos);
        jPGraficos.setLayout(jPGraficosLayout);
        jPGraficosLayout.setHorizontalGroup(
            jPGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPGraficosLayout.setVerticalGroup(
            jPGraficosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        jLDatos.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLDatos.setForeground(new java.awt.Color(255, 255, 255));
        jLDatos.setText("Datos para estadísticas:");

        jPDatosGraficos.setLayout(new java.awt.GridLayout(1, 0, 10, 40));

        jYear.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jPDatosGraficos.add(jYear);

        jSpinPeriodo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jSpinPeriodo.setMaximum(2);
        jSpinPeriodo.setMinimum(1);
        jSpinPeriodo.setValue(1);
        jPDatosGraficos.add(jSpinPeriodo);

        JBtnFiltrar.setBackground(new java.awt.Color(172, 0, 0));
        JBtnFiltrar.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        JBtnFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        JBtnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/filtrar.png"))); // NOI18N
        JBtnFiltrar.setText("Filtrar");
        JBtnFiltrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtnFiltrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPOpcionGrafi.setBackground(new java.awt.Color(12, 32, 65));
        jPOpcionGrafi.setLayout(new java.awt.GridLayout(2, 1, 0, 20));

        jRbtnGraficoBarra.setBackground(new java.awt.Color(15, 32, 65));
        buttonGroupGrafico.add(jRbtnGraficoBarra);
        jRbtnGraficoBarra.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jRbtnGraficoBarra.setForeground(new java.awt.Color(255, 255, 255));
        jRbtnGraficoBarra.setText("Gráfico barra");
        jPOpcionGrafi.add(jRbtnGraficoBarra);

        jRbtnGraficoPastel.setBackground(new java.awt.Color(15, 32, 65));
        buttonGroupGrafico.add(jRbtnGraficoPastel);
        jRbtnGraficoPastel.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jRbtnGraficoPastel.setForeground(new java.awt.Color(255, 255, 255));
        jRbtnGraficoPastel.setText("Gráfico pastel");
        jPOpcionGrafi.add(jRbtnGraficoPastel);

        javax.swing.GroupLayout jPContentLayout = new javax.swing.GroupLayout(jPContent);
        jPContent.setLayout(jPContentLayout);
        jPContentLayout.setHorizontalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLDatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPDatosGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPOpcionGrafi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBtnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 598, Short.MAX_VALUE))
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPGraficos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
        );
        jPContentLayout.setVerticalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPGraficos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPContentLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(JBtnFiltrar)
                        .addGap(8, 8, 8))
                    .addGroup(jPContentLayout.createSequentialGroup()
                        .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPContentLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPDatosGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLDatos)))
                            .addGroup(jPContentLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPOpcionGrafi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );

        jPTitleNewProject.setBackground(new java.awt.Color(15, 32, 65));
        jPTitleNewProject.setForeground(new java.awt.Color(255, 255, 255));

        jBtnEstadistica.setBackground(new java.awt.Color(172, 0, 0));
        jBtnEstadistica.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnEstadistica.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEstadistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/estadisticasBig.png"))); // NOI18N
        jBtnEstadistica.setText("Estadisticas");
        jBtnEstadistica.setBorderPainted(false);
        jBtnEstadistica.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnEstadistica.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPTitleNewProject.add(jBtnEstadistica);

        jPHead.setBackground(new java.awt.Color(15, 32, 65));
        jPHead.setLayout(new javax.swing.BoxLayout(jPHead, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect.setBackground(new java.awt.Color(15, 32, 65));
        lbTitleProyect.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbTitleProyect.setForeground(new java.awt.Color(255, 255, 255));
        lbTitleProyect.setText("Sistema gestor de proyectos academicos");
        jPHead.add(lbTitleProyect);

        jPOpcLogin.setBackground(new java.awt.Color(236, 230, 240));
        jPOpcLogin.setLayout(new java.awt.GridLayout(1, 1, 1, 0));

        jBtnLoginU.setBackground(new java.awt.Color(172, 0, 0));
        jBtnLoginU.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnLoginU.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLoginU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/usuario.png"))); // NOI18N
        jBtnLoginU.setText("My User");
        jBtnLoginU.setBorder(null);
        jBtnLoginU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnLoginU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLoginU.setIconTextGap(5);
        jBtnLoginU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnLoginU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcLogin.add(jBtnLoginU);

        jPHead.add(jPOpcLogin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPTitleNewProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPTitleNewProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnFiltrar;
    private javax.swing.ButtonGroup buttonGroupGrafico;
    private javax.swing.JButton jBtnEstadistica;
    private javax.swing.JButton jBtnLoginU;
    private javax.swing.JLabel jLDatos;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPDatosGraficos;
    private javax.swing.JPanel jPGraficos;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPOpcLogin;
    private javax.swing.JPanel jPOpcionGrafi;
    private javax.swing.JPanel jPTitleNewProject;
    private javax.swing.JRadioButton jRbtnGraficoBarra;
    private javax.swing.JRadioButton jRbtnGraficoPastel;
    private com.toedter.components.JSpinField jSpinPeriodo;
    private com.toedter.calendar.JYearChooser jYear;
    private java.awt.Label lbTitleProyect;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(String mensaje) {
        System.out.println("Actualizando desde GUI statics");
    }
}
