/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI;

import co.edu.unicauca.academicproject.GUI.controller.Home.ControllerHomeWithOutLog;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUIHomeWithOutLog extends javax.swing.JFrame {

    /**
     * Creates new form GUIHomeWithOutLog
     */
    public GUIHomeWithOutLog() {

        initComponents();
        ControllerHomeWithOutLog controller = new ControllerHomeWithOutLog(this);
    }

    public JButton getjBtnLoginU() {
        return jBtnLoginU;
    }

    public JButton getjBtnNewUser() {
        return jBtnNewUser;
    }

    
    public JTable getjTableProjects() {
        return jTableProjects;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPContent = new javax.swing.JPanel();
        jLTittleProjects = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjects = new javax.swing.JTable();
        jPSearchBar = new javax.swing.JPanel();
        jCBSelecFilter = new javax.swing.JComboBox<>();
        jFieldSearchProyect = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jButtonQuitF = new javax.swing.JButton();
        jPHead1 = new javax.swing.JPanel();
        lbTitleProyect1 = new java.awt.Label();
        jPOpcLogin1 = new javax.swing.JPanel();
        jBtnNewUser = new javax.swing.JButton();
        jBtnLoginU = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(15, 32, 65));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(850, 500));

        jPContent.setBackground(new java.awt.Color(15, 32, 65));
        jPContent.setForeground(new java.awt.Color(15, 32, 65));

        jLTittleProjects.setBackground(new java.awt.Color(15, 32, 65));
        jLTittleProjects.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLTittleProjects.setForeground(new java.awt.Color(255, 255, 255));
        jLTittleProjects.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleProjects.setText("Proyectos disponibles");
        jLTittleProjects.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTableProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableProjects.setCellSelectionEnabled(true);
        jTableProjects.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTableProjects.setShowGrid(true);
        jScrollPane1.setViewportView(jTableProjects);

        javax.swing.GroupLayout jPContentLayout = new javax.swing.GroupLayout(jPContent);
        jPContent.setLayout(jPContentLayout);
        jPContentLayout.setHorizontalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLTittleProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPContentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
        );
        jPContentLayout.setVerticalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addComponent(jLTittleProjects, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPSearchBar.setBackground(new java.awt.Color(15, 32, 65));
        jPSearchBar.setLayout(new java.awt.GridBagLayout());

        jCBSelecFilter.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jCBSelecFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Nombre", "Por Compañia", "Por Estudiante" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPSearchBar.add(jCBSelecFilter, gridBagConstraints);

        jFieldSearchProyect.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jFieldSearchProyect.setText("Ingrese un proyecto a buscar...");
        jFieldSearchProyect.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jFieldSearchProyect.setMinimumSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        jPSearchBar.add(jFieldSearchProyect, gridBagConstraints);

        jBtnSearch.setBackground(new java.awt.Color(15, 32, 65));
        jBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/buscar.png"))); // NOI18N
        jBtnSearch.setBorderPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPSearchBar.add(jBtnSearch, gridBagConstraints);

        jButtonQuitF.setText("Quitar filtro");
        jPSearchBar.add(jButtonQuitF, new java.awt.GridBagConstraints());
        jButtonQuitF.setVisible(false);

        jPHead1.setBackground(new java.awt.Color(15, 32, 65));
        jPHead1.setLayout(new javax.swing.BoxLayout(jPHead1, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect1.setBackground(new java.awt.Color(15, 32, 65));
        lbTitleProyect1.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        lbTitleProyect1.setForeground(new java.awt.Color(255, 255, 255));
        lbTitleProyect1.setText("Sistema gestor de proyectos academicos");
        jPHead1.add(lbTitleProyect1);

        jPOpcLogin1.setBackground(new java.awt.Color(15, 32, 65));
        jPOpcLogin1.setLayout(new java.awt.GridLayout(1, 2, 1, 0));

        jBtnNewUser.setBackground(new java.awt.Color(175, 0, 0));
        jBtnNewUser.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jBtnNewUser.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/mas.png"))); // NOI18N
        jBtnNewUser.setText("Crear cuenta");
        jBtnNewUser.setToolTipText("");
        jBtnNewUser.setBorder(null);
        jBtnNewUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnNewUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnNewUser.setIconTextGap(1);
        jBtnNewUser.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jBtnNewUser.setMaximumSize(new java.awt.Dimension(100, 70));
        jBtnNewUser.setMinimumSize(new java.awt.Dimension(100, 70));
        jBtnNewUser.setOpaque(true);
        jBtnNewUser.setPreferredSize(new java.awt.Dimension(112, 70));
        jBtnNewUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnNewUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcLogin1.add(jBtnNewUser);

        jBtnLoginU.setBackground(new java.awt.Color(175, 0, 0));
        jBtnLoginU.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jBtnLoginU.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLoginU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/usuario.png"))); // NOI18N
        jBtnLoginU.setText("Iniciar Sesión");
        jBtnLoginU.setBorder(null);
        jBtnLoginU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnLoginU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLoginU.setIconTextGap(5);
        jBtnLoginU.setOpaque(true);
        jBtnLoginU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnLoginU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcLogin1.add(jBtnLoginU);

        jPHead1.add(jPOpcLogin1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPSearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLoginU;
    private javax.swing.JButton jBtnNewUser;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jButtonQuitF;
    private javax.swing.JComboBox<String> jCBSelecFilter;
    private javax.swing.JTextField jFieldSearchProyect;
    private javax.swing.JLabel jLTittleProjects;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead1;
    private javax.swing.JPanel jPOpcLogin1;
    private javax.swing.JPanel jPSearchBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProjects;
    private java.awt.Label lbTitleProyect1;
    // End of variables declaration//GEN-END:variables
}
