/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI;

import co.edu.unicauca.academicproject.GUI.controller.Home.ControllerHomeWithLog;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUIHomeWithLog extends javax.swing.JFrame {

    /**
     * Creates new form GUIHineWithLog
     */

    private String rol;
    private String idUser;
    public GUIHomeWithLog(String idUser,String rol,String token) {
        initComponents();
        this.rol = rol;
        this.idUser = idUser;
        ControllerHomeWithLog controller = new ControllerHomeWithLog(this,token);
    }

    public String getidUser() {
        return idUser;
    }

    public JButton getjBtnAsignar() {
        return jBtnAsignar;
    }

    public JButton getjBtnCoordiSoli() {
        return jBtnCoordiSoli;
    }

    public JButton getjBtnGetOut() {
        return jBtnGetOut;
    }

    public JButton getjBtnLoginU() {
        return jBtnLoginU;
    }

    public JButton getjBtnMyPubli() {
        return jBtnMyPubli;
    }

    public JButton getjBtnNewPubli() {
        return jBtnNewPubli;
    }

    public JButton getjBtnSearch() {
        return jBtnSearch;
    }

    public JButton getjBtnSolicitudes() {
        return jBtnSolicitudes;
    }

    public JButton getjBtnUsersSistema() {
        return jBtnUsersSistema;
    }

    public JButton getjButtonQuitF() {
        return jButtonQuitF;
    }
    
    public String getRol() {
        return rol;
    }

    public String getIdUser() {
        return idUser;
    }
    
    public JPanel getJPoptions(){
        return jPOptions;
    }


    public JTable getjTableProjects() {
        return jTableProjects;
    }
    
    public JPanel getJPanelStudent(){
        return jPOpcionStudent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPHead = new javax.swing.JPanel();
        lbTitleProyect = new java.awt.Label();
        jPOpcLogin = new javax.swing.JPanel();
        jBtnLoginU = new javax.swing.JButton();
        jPSearchBar = new javax.swing.JPanel();
        jCBSelecFilter = new javax.swing.JComboBox<>();
        jFieldSearchProyect = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jButtonQuitF = new javax.swing.JButton();
        jPContent = new javax.swing.JPanel();
        jPOptions = new javax.swing.JPanel();
        jPOpcionCompany = new javax.swing.JPanel();
        jBtnNewPubli = new javax.swing.JButton();
        jBtnMyPubli = new javax.swing.JButton();
        jPOpcionCoordi = new javax.swing.JPanel();
        jBtnSolicitudes = new javax.swing.JButton();
        jBtnAsignar = new javax.swing.JButton();
        jPOpcionStudent = new javax.swing.JPanel();
        jPOpcionAdmin = new javax.swing.JPanel();
        jBtnUsersSistema = new javax.swing.JButton();
        jBtnCoordiSoli = new javax.swing.JButton();
        jPPublis = new javax.swing.JPanel();
        jLTitleProjects = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProjects = new javax.swing.JTable();
        jPSideMenu = new javax.swing.JPanel();
        jLTittleMenu = new javax.swing.JLabel();
        jBtnGetOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Home");
        setMinimumSize(new java.awt.Dimension(900, 500));

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setLayout(new javax.swing.BoxLayout(jPHead, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect.setBackground(new java.awt.Color(15, 32, 65));
        lbTitleProyect.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        lbTitleProyect.setForeground(new java.awt.Color(255, 255, 255));
        lbTitleProyect.setText("Sistema gestor de proyectos academicos");
        jPHead.add(lbTitleProyect);

        jPOpcLogin.setBackground(new java.awt.Color(236, 230, 240));
        jPOpcLogin.setLayout(new java.awt.GridLayout(1, 1));

        jBtnLoginU.setBackground(new java.awt.Color(175, 0, 0));
        jBtnLoginU.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnLoginU.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLoginU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/usuario.png"))); // NOI18N
        jBtnLoginU.setText("Mi user");
        jBtnLoginU.setBorder(null);
        jBtnLoginU.setBorderPainted(false);
        jBtnLoginU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnLoginU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnLoginU.setIconTextGap(5);
        jBtnLoginU.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnLoginU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcLogin.add(jBtnLoginU);

        jPHead.add(jPOpcLogin);

        jPSearchBar.setBackground(new java.awt.Color(15, 32, 65));
        jPSearchBar.setLayout(new java.awt.GridBagLayout());

        jCBSelecFilter.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jCBSelecFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Nombre", "Por Compañia", "Por Estudiante" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 10);
        jPSearchBar.add(jCBSelecFilter, gridBagConstraints);

        jFieldSearchProyect.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jFieldSearchProyect.setText("Ingrese un proyecto a buscar...");
        jFieldSearchProyect.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jFieldSearchProyect.setMinimumSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        jPSearchBar.add(jFieldSearchProyect, gridBagConstraints);

        jBtnSearch.setBackground(new java.awt.Color(15, 32, 65));
        jBtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/buscar.png"))); // NOI18N
        jBtnSearch.setBorderPainted(false);
        jPSearchBar.add(jBtnSearch, new java.awt.GridBagConstraints());

        jButtonQuitF.setText("Quitar filtro");
        jPSearchBar.add(jButtonQuitF, new java.awt.GridBagConstraints());
        jButtonQuitF.setVisible(false);

        jPContent.setBackground(new java.awt.Color(236, 230, 240));

        jPOptions.setBackground(new java.awt.Color(236, 230, 240));
        jPOptions.setLayout(new java.awt.CardLayout());

        jPOpcionCompany.setBackground(new java.awt.Color(251, 219, 147));

        jBtnNewPubli.setBackground(new java.awt.Color(175, 0, 0));
        jBtnNewPubli.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnNewPubli.setForeground(new java.awt.Color(255, 255, 255));
        jBtnNewPubli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/newPubli.png"))); // NOI18N
        jBtnNewPubli.setText("Nueva publicación");
        jBtnNewPubli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnNewPubli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcionCompany.add(jBtnNewPubli);

        jBtnMyPubli.setBackground(new java.awt.Color(175, 0, 0));
        jBtnMyPubli.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnMyPubli.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMyPubli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MyPubli.png"))); // NOI18N
        jBtnMyPubli.setText("Mis publicaciones");
        jBtnMyPubli.setToolTipText("");
        jBtnMyPubli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnMyPubli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcionCompany.add(jBtnMyPubli);

        jPOptions.add(jPOpcionCompany, "Empresa");

        jPOpcionCoordi.setBackground(new java.awt.Color(190, 91, 80));

        jBtnSolicitudes.setBackground(new java.awt.Color(172, 0, 0));
        jBtnSolicitudes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnSolicitudes.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSolicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/notificacion.png"))); // NOI18N
        jBtnSolicitudes.setText("Solicitudes");
        jBtnSolicitudes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnSolicitudes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jBtnAsignar.setBackground(new java.awt.Color(172, 0, 0));
        jBtnAsignar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnAsignar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/derecha.png"))); // NOI18N
        jBtnAsignar.setText("Asignar Proyecto");
        jBtnAsignar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAsignar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPOpcionCoordiLayout = new javax.swing.GroupLayout(jPOpcionCoordi);
        jPOpcionCoordi.setLayout(jPOpcionCoordiLayout);
        jPOpcionCoordiLayout.setHorizontalGroup(
            jPOpcionCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionCoordiLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jBtnSolicitudes)
                .addGap(54, 54, 54)
                .addComponent(jBtnAsignar)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPOpcionCoordiLayout.setVerticalGroup(
            jPOpcionCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionCoordiLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPOpcionCoordiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPOptions.add(jPOpcionCoordi, "Coordinador");

        jPOpcionStudent.setBackground(new java.awt.Color(236, 230, 240));

        javax.swing.GroupLayout jPOpcionStudentLayout = new javax.swing.GroupLayout(jPOpcionStudent);
        jPOpcionStudent.setLayout(jPOpcionStudentLayout);
        jPOpcionStudentLayout.setHorizontalGroup(
            jPOpcionStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        jPOpcionStudentLayout.setVerticalGroup(
            jPOpcionStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPOptions.add(jPOpcionStudent, "Estudiante");

        jPOpcionAdmin.setBackground(new java.awt.Color(255, 255, 255));
        jPOpcionAdmin.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 10));

        jBtnUsersSistema.setBackground(new java.awt.Color(172, 0, 0));
        jBtnUsersSistema.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnUsersSistema.setForeground(new java.awt.Color(255, 255, 255));
        jBtnUsersSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/audiencia.png"))); // NOI18N
        jBtnUsersSistema.setText("VER USUARIOS EN EL SISTEMA");
        jBtnUsersSistema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnUsersSistema.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcionAdmin.add(jBtnUsersSistema);

        jBtnCoordiSoli.setBackground(new java.awt.Color(172, 0, 0));
        jBtnCoordiSoli.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnCoordiSoli.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCoordiSoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/coordi.png"))); // NOI18N
        jBtnCoordiSoli.setText("GESTION DE COORDINADORES");
        jBtnCoordiSoli.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnCoordiSoli.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPOpcionAdmin.add(jBtnCoordiSoli);

        jPOptions.add(jPOpcionAdmin, "Admin");

        jPPublis.setBackground(new java.awt.Color(15, 32, 65));

        jLTitleProjects.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        jLTitleProjects.setForeground(new java.awt.Color(255, 255, 255));
        jLTitleProjects.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitleProjects.setText("Proyectos disponibles");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableProjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProjects);

        javax.swing.GroupLayout jPPublisLayout = new javax.swing.GroupLayout(jPPublis);
        jPPublis.setLayout(jPPublisLayout);
        jPPublisLayout.setHorizontalGroup(
            jPPublisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPublisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitleProjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPPublisLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPPublisLayout.setVerticalGroup(
            jPPublisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPublisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitleProjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPContentLayout = new javax.swing.GroupLayout(jPContent);
        jPContent.setLayout(jPContentLayout);
        jPContentLayout.setHorizontalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPOptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPPublis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPContentLayout.setVerticalGroup(
            jPContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContentLayout.createSequentialGroup()
                .addComponent(jPOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPPublis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPSideMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPSideMenu.setLayout(new java.awt.GridBagLayout());

        jLTittleMenu.setBackground(new java.awt.Color(0, 0, 0));
        jLTittleMenu.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLTittleMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleMenu.setText("Menú");
        jLTittleMenu.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPSideMenu.add(jLTittleMenu, gridBagConstraints);

        jBtnGetOut.setBackground(new java.awt.Color(175, 0, 0));
        jBtnGetOut.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jBtnGetOut.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGetOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/salir.png"))); // NOI18N
        jBtnGetOut.setText("Salir");
        jBtnGetOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnGetOut.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jBtnGetOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 100, 0);
        jPSideMenu.add(jBtnGetOut, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPSearchBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPSideMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPSideMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAsignar;
    private javax.swing.JButton jBtnCoordiSoli;
    private javax.swing.JButton jBtnGetOut;
    private javax.swing.JButton jBtnLoginU;
    private javax.swing.JButton jBtnMyPubli;
    private javax.swing.JButton jBtnNewPubli;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jBtnSolicitudes;
    private javax.swing.JButton jBtnUsersSistema;
    private javax.swing.JButton jButtonQuitF;
    private javax.swing.JComboBox<String> jCBSelecFilter;
    private javax.swing.JTextField jFieldSearchProyect;
    private javax.swing.JLabel jLTitleProjects;
    private javax.swing.JLabel jLTittleMenu;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPOpcLogin;
    private javax.swing.JPanel jPOpcionAdmin;
    private javax.swing.JPanel jPOpcionCompany;
    private javax.swing.JPanel jPOpcionCoordi;
    private javax.swing.JPanel jPOpcionStudent;
    private javax.swing.JPanel jPOptions;
    private javax.swing.JPanel jPPublis;
    private javax.swing.JPanel jPSearchBar;
    private javax.swing.JPanel jPSideMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProjects;
    private java.awt.Label lbTitleProyect;
    // End of variables declaration//GEN-END:variables
}
