/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.academicproject.GUI;

import co.edu.unicauca.academicproject.GUI.controller.RegisterUser.ControllerRegisterUser;

import javax.swing.*;

/**
 *
 * @author lopez
 */
public class GUIRegisteredUser extends javax.swing.JFrame {

    /**
     * Creates new form GUIRegisteredUser
     */
    public GUIRegisteredUser() {
        initComponents();
        ControllerRegisterUser controller = new ControllerRegisterUser(this);
    }

    public JLabel getjLTittleNewUser() {
        return jLTittleNewUser;
    }

    public JButton getjBtnBackSelectUser() {
        return jBtnBackSelectUser;
    }



    public JButton getjBtnSaveCompany() {
        return jBtnSaveCompany;
    }

    public JButton getjBtnSaveCoordi() {
        return jBtnSaveCoordi;
    }

    public JButton getjBtnSaveStudent() {
        return jBtnSaveStudent;
    }

    public ButtonGroup getButtonGroupRol() {
        return buttonGroupRol;
    }

    public JRadioButton getjRbtnCompany() {
        return jRbtnCompany;
    }

    public JRadioButton getjRbtnCoordi() {
        return jRbtnCoordi;
    }

    public JRadioButton getjRbtnStudent() {
        return jRbtnStudent;
    }

    public JPanel getjPContent() {
        return jPContent;
    }

    public JPanel getjPRegisterUser() {
        return jPRegisterUser;
    }

    public JPanel getjPRolInformation() {
        return jPRolInformation;
    }

    public JComboBox<String> getjCBProgramCoordi() {
        return jCBProgramCoordi;
    }

    public JComboBox<String> getjCBSectorCompany() {
        return jCBSectorCompany;
    }

    public JTextField getjFieldCodeStudent() {
        return jFieldCodeStudent;
    }

    public JTextField getjFieldEmailStudent() {
        return jFieldEmailStudent;
    }

    public JTextField getjFieldNameStudent() {
        return jFieldNameStudent;
    }

    public JPasswordField getjFieldPassWordStudent() {
        return jFieldPassWordStudent;
    }

    public JTextField getjFieldTelStudent() {
        return jFieldTelStudent;
    }

    public JTextField getjFieldNitCompany() {
        return jFieldNitCompany;
    }

    public JTextField getjFieldNameCompany() {
        return jFieldNameCompany;
    }

    public JPasswordField getjFieldPassWordCompany() {
        return jFieldPassWordCompany;
    }

    public JTextField getjFieldTelCompany() {
        return jFieldTelCompany;
    }

    public JTextField getjFieldWebCompany() {
        return jFieldWebCompany;
    }

    public JTextField getjFieldEmailCompany() {
        return jFieldEmailCompany;
    }

    public JTextField getjFieldCodeCoordi() {
        return jFieldCodeCoordi;
    }

    public JTextField getjFieldEmailCoordi() {
        return jFieldEmailCoordi;
    }

    public JTextField getjFieldNameCoordi() {
        return jFieldNameCoordi;
    }

    public JPasswordField getjFieldPassWordCoordi() {
        return jFieldPassWordCoordi;
    }

    public JTextField getjFieldTelCoordi() {
        return jFieldTelCoordi;
    }

    public JCheckBox getjCheckSeePassCompany() {
        return jCheckSeePassCompany;
    }

    public JCheckBox getjCheckSeePassCoordi() {
        return jCheckSeePassCoordi;
    }

    public JCheckBox getjCheckSeePassStudent() {
        return jCheckSeePassStudent;
    }

    public JTextField getjFielPuestoAse() {
        return jFielPuestoAse;
    }

    public JTextField getjFieldApellidoAse() {
        return jFieldApellidoAse;
    }

    public JTextField getjFieldNombreAse() {
        return jFieldNombreAse;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupRol = new javax.swing.ButtonGroup();
        jPTittleNewUser = new javax.swing.JPanel();
        jLTittleNewUser = new javax.swing.JLabel();
        jPContent = new javax.swing.JPanel();
        jPSelecRol = new javax.swing.JPanel();
        jLSelectRol = new javax.swing.JLabel();
        jRbtnStudent = new javax.swing.JRadioButton();
        jRbtnCompany = new javax.swing.JRadioButton();
        jRbtnCoordi = new javax.swing.JRadioButton();
        jPRolInformation = new javax.swing.JPanel();
        jPCompanyInformation = new javax.swing.JPanel();
        jLTittleNewCompany = new javax.swing.JLabel();
        jScrolInfoCompany = new javax.swing.JScrollPane();
        jTextAInfoCompany = new javax.swing.JTextArea();
        jPCoordinatorInformation = new javax.swing.JPanel();
        jLTittleNewCompany1 = new javax.swing.JLabel();
        jScrolInfoCoordi = new javax.swing.JScrollPane();
        jTextAInfoCoordi = new javax.swing.JTextArea();
        jPStudentInformation = new javax.swing.JPanel();
        jLTittleNewStudent = new javax.swing.JLabel();
        jScrolInfoStudent = new javax.swing.JScrollPane();
        jTextAInfoStudent = new javax.swing.JTextArea();
        jPRegisterUser = new javax.swing.JPanel();
        jPCoordiRegister = new javax.swing.JPanel();
        jBtnSaveCoordi = new javax.swing.JButton();
        jFieldPassWordCoordi = new javax.swing.JPasswordField();
        jCheckSeePassCoordi = new javax.swing.JCheckBox();
        jLPasswordCoordi = new javax.swing.JLabel();
        jFieldEmailCoordi = new javax.swing.JTextField();
        jLEmailCoordi = new javax.swing.JLabel();
        jFieldTelCoordi = new javax.swing.JTextField();
        jLTelCoordi = new javax.swing.JLabel();
        jFieldCodeCoordi = new javax.swing.JTextField();
        jLCodeCoordi = new javax.swing.JLabel();
        jFieldNameCoordi = new javax.swing.JTextField();
        jLNameCoordi = new javax.swing.JLabel();
        jCBProgramCoordi = new javax.swing.JComboBox<>();
        jLProgramCoordi = new javax.swing.JLabel();
        jPStudentRegister = new javax.swing.JPanel();
        jLNameStudent = new javax.swing.JLabel();
        jFieldNameStudent = new javax.swing.JTextField();
        jLCodeStudent = new javax.swing.JLabel();
        jFieldCodeStudent = new javax.swing.JTextField();
        jLTelStudent = new javax.swing.JLabel();
        jFieldTelStudent = new javax.swing.JTextField();
        jLEmailStudent = new javax.swing.JLabel();
        jFieldEmailStudent = new javax.swing.JTextField();
        jLPasswordStudent = new javax.swing.JLabel();
        jCheckSeePassStudent = new javax.swing.JCheckBox();
        jFieldPassWordStudent = new javax.swing.JPasswordField();
        jBtnSaveStudent = new javax.swing.JButton();
        jPCompanyRegister = new javax.swing.JPanel();
        jLNitCompany = new javax.swing.JLabel();
        jFieldNitCompany = new javax.swing.JTextField();
        jLNameCompany = new javax.swing.JLabel();
        jFieldNameCompany = new javax.swing.JTextField();
        jLTelCompany = new javax.swing.JLabel();
        jFieldTelCompany = new javax.swing.JTextField();
        jLWebCompany = new javax.swing.JLabel();
        jFieldWebCompany = new javax.swing.JTextField();
        jLSectorCompany = new javax.swing.JLabel();
        jCBSectorCompany = new javax.swing.JComboBox<>();
        jLEmailCompany = new javax.swing.JLabel();
        jFieldEmailCompany = new javax.swing.JTextField();
        jLPasswordCompany = new javax.swing.JLabel();
        jFieldPassWordCompany = new javax.swing.JPasswordField();
        jCheckSeePassCompany = new javax.swing.JCheckBox();
        jBtnSaveCompany = new javax.swing.JButton();
        jLDatosContacto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jFieldNombreAse = new javax.swing.JTextField();
        jLApellidoAse = new javax.swing.JLabel();
        jFieldApellidoAse = new javax.swing.JTextField();
        jLPuestoAse = new javax.swing.JLabel();
        jFielPuestoAse = new javax.swing.JTextField();
        jPButtom = new javax.swing.JPanel();
        jBtnBackSelectUser = new javax.swing.JButton();
        jPHead = new javax.swing.JPanel();
        lbTitleProyect = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo registro");
        setMinimumSize(new java.awt.Dimension(820, 650));

        jPTittleNewUser.setBackground(new java.awt.Color(255, 255, 255));

        jLTittleNewUser.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLTittleNewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/usuario.png"))); // NOI18N
        jLTittleNewUser.setText("Nuevo Registro ");
        jLTittleNewUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPTittleNewUser.add(jLTittleNewUser);

        jPContent.setBackground(new java.awt.Color(15, 32, 65));
        jPContent.setForeground(new java.awt.Color(255, 255, 255));
        jPContent.setLayout(new java.awt.GridBagLayout());

        jPSelecRol.setBackground(new java.awt.Color(255, 255, 255));

        jLSelectRol.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLSelectRol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSelectRol.setText("Seleccione su rol :");

        jRbtnStudent.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupRol.add(jRbtnStudent);
        jRbtnStudent.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jRbtnStudent.setText("Estudiante");

        buttonGroupRol.add(jRbtnCompany);
        jRbtnCompany.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jRbtnCompany.setText("Empresa");

        buttonGroupRol.add(jRbtnCoordi);
        jRbtnCoordi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jRbtnCoordi.setText("Coordinador");

        javax.swing.GroupLayout jPSelecRolLayout = new javax.swing.GroupLayout(jPSelecRol);
        jPSelecRol.setLayout(jPSelecRolLayout);
        jPSelecRolLayout.setHorizontalGroup(
            jPSelecRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLSelectRol, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPSelecRolLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jRbtnStudent)
                .addGap(20, 20, 20)
                .addComponent(jRbtnCompany)
                .addGap(21, 21, 21)
                .addComponent(jRbtnCoordi))
        );
        jPSelecRolLayout.setVerticalGroup(
            jPSelecRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSelecRolLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLSelectRol)
                .addGap(18, 18, 18)
                .addGroup(jPSelecRolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRbtnStudent)
                    .addComponent(jRbtnCompany)
                    .addComponent(jRbtnCoordi)))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        jPContent.add(jPSelecRol, gridBagConstraints);

        jPRolInformation.setBackground(new java.awt.Color(255, 255, 255));
        jPRolInformation.setForeground(new java.awt.Color(255, 255, 255));
        jPRolInformation.setName(""); // NOI18N
        jPRolInformation.setLayout(new java.awt.CardLayout());

        jPCompanyInformation.setBackground(new java.awt.Color(255, 255, 255));
        jPCompanyInformation.setName(""); // NOI18N

        jLTittleNewCompany.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLTittleNewCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleNewCompany.setText("Nueva Empresa");
        jLTittleNewCompany.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextAInfoCompany.setEditable(false);
        jTextAInfoCompany.setBackground(new java.awt.Color(255, 255, 255));
        jTextAInfoCompany.setColumns(20);
        jTextAInfoCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextAInfoCompany.setLineWrap(true);
        jTextAInfoCompany.setRows(5);
        jTextAInfoCompany.setText("Empresas interesadas en publicar proyectos para asignarlos a estudiantes ");
        jScrolInfoCompany.setViewportView(jTextAInfoCompany);

        javax.swing.GroupLayout jPCompanyInformationLayout = new javax.swing.GroupLayout(jPCompanyInformation);
        jPCompanyInformation.setLayout(jPCompanyInformationLayout);
        jPCompanyInformationLayout.setHorizontalGroup(
            jPCompanyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCompanyInformationLayout.createSequentialGroup()
                .addGroup(jPCompanyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCompanyInformationLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLTittleNewCompany))
                    .addGroup(jPCompanyInformationLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrolInfoCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPCompanyInformationLayout.setVerticalGroup(
            jPCompanyInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCompanyInformationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLTittleNewCompany)
                .addGap(18, 18, 18)
                .addComponent(jScrolInfoCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPRolInformation.add(jPCompanyInformation, "Empresa");

        jPCoordinatorInformation.setBackground(new java.awt.Color(255, 255, 255));
        jPCoordinatorInformation.setForeground(new java.awt.Color(255, 255, 255));
        jPCoordinatorInformation.setName("CoordiInformation"); // NOI18N

        jLTittleNewCompany1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLTittleNewCompany1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleNewCompany1.setText("Nuevo coordinador");
        jLTittleNewCompany1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextAInfoCoordi.setEditable(false);
        jTextAInfoCoordi.setBackground(new java.awt.Color(255, 255, 255));
        jTextAInfoCoordi.setColumns(20);
        jTextAInfoCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextAInfoCoordi.setLineWrap(true);
        jTextAInfoCoordi.setRows(5);
        jTextAInfoCoordi.setText("Persona encargada para la gestión de proyectos entre empresas y estudiantes. Necesita la validación del administrador del sistema para la creación de la cuenta. ");
        jScrolInfoCoordi.setViewportView(jTextAInfoCoordi);

        javax.swing.GroupLayout jPCoordinatorInformationLayout = new javax.swing.GroupLayout(jPCoordinatorInformation);
        jPCoordinatorInformation.setLayout(jPCoordinatorInformationLayout);
        jPCoordinatorInformationLayout.setHorizontalGroup(
            jPCoordinatorInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordinatorInformationLayout.createSequentialGroup()
                .addGroup(jPCoordinatorInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCoordinatorInformationLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrolInfoCoordi, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCoordinatorInformationLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLTittleNewCompany1)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPCoordinatorInformationLayout.setVerticalGroup(
            jPCoordinatorInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCoordinatorInformationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLTittleNewCompany1)
                .addGap(18, 18, 18)
                .addComponent(jScrolInfoCoordi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPRolInformation.add(jPCoordinatorInformation, "Coordi");

        jPStudentInformation.setBackground(new java.awt.Color(255, 255, 255));
        jPStudentInformation.setName(""); // NOI18N

        jLTittleNewStudent.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLTittleNewStudent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTittleNewStudent.setText("Nuevo estudiante");
        jLTittleNewStudent.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jTextAInfoStudent.setEditable(false);
        jTextAInfoStudent.setBackground(new java.awt.Color(255, 255, 255));
        jTextAInfoStudent.setColumns(20);
        jTextAInfoStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextAInfoStudent.setLineWrap(true);
        jTextAInfoStudent.setRows(5);
        jTextAInfoStudent.setText("Estudiantes de la Universidad del Cauca que deseen la creación de una cuenta para postularse a proyectos que publican empresas.");
        jScrolInfoStudent.setViewportView(jTextAInfoStudent);

        javax.swing.GroupLayout jPStudentInformationLayout = new javax.swing.GroupLayout(jPStudentInformation);
        jPStudentInformation.setLayout(jPStudentInformationLayout);
        jPStudentInformationLayout.setHorizontalGroup(
            jPStudentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPStudentInformationLayout.createSequentialGroup()
                .addGroup(jPStudentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPStudentInformationLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrolInfoStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPStudentInformationLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLTittleNewStudent)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPStudentInformationLayout.setVerticalGroup(
            jPStudentInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPStudentInformationLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLTittleNewStudent)
                .addGap(18, 18, 18)
                .addComponent(jScrolInfoStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jPRolInformation.add(jPStudentInformation, "Estudiante");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.ipady = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPContent.add(jPRolInformation, gridBagConstraints);

        jPRegisterUser.setBackground(new java.awt.Color(255, 255, 255));
        jPRegisterUser.setLayout(new java.awt.CardLayout());

        jPCoordiRegister.setBackground(new java.awt.Color(255, 255, 255));
        jPCoordiRegister.setName("CoordiRegister"); // NOI18N
        jPCoordiRegister.setLayout(new java.awt.GridBagLayout());

        jBtnSaveCoordi.setBackground(new java.awt.Color(172, 0, 0));
        jBtnSaveCoordi.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jBtnSaveCoordi.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSaveCoordi.setText("GUARDAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 108, 35, 0);
        jPCoordiRegister.add(jBtnSaveCoordi, gridBagConstraints);

        jFieldPassWordCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldPassWordCoordi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldPassWordCoordi.setText("jPasswordField1");
        jFieldPassWordCoordi.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 99, 0, 0);
        jPCoordiRegister.add(jFieldPassWordCoordi, gridBagConstraints);

        jCheckSeePassCoordi.setText("Mostrar clave");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 100);
        jPCoordiRegister.add(jCheckSeePassCoordi, gridBagConstraints);

        jLPasswordCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLPasswordCoordi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLPasswordCoordi.setText("Clave:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCoordiRegister.add(jLPasswordCoordi, gridBagConstraints);

        jFieldEmailCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldEmailCoordi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldEmailCoordi.setText("lopez@gmail.com");
        jFieldEmailCoordi.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCoordiRegister.add(jFieldEmailCoordi, gridBagConstraints);

        jLEmailCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLEmailCoordi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLEmailCoordi.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCoordiRegister.add(jLEmailCoordi, gridBagConstraints);

        jFieldTelCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldTelCoordi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldTelCoordi.setText("317123");
        jFieldTelCoordi.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCoordiRegister.add(jFieldTelCoordi, gridBagConstraints);

        jLTelCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLTelCoordi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLTelCoordi.setText("Telefono de contacto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCoordiRegister.add(jLTelCoordi, gridBagConstraints);

        jFieldCodeCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldCodeCoordi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldCodeCoordi.setText("1046123");
        jFieldCodeCoordi.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCoordiRegister.add(jFieldCodeCoordi, gridBagConstraints);

        jLCodeCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLCodeCoordi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLCodeCoordi.setText("Codigo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCoordiRegister.add(jLCodeCoordi, gridBagConstraints);

        jFieldNameCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldNameCoordi.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldNameCoordi.setText("Julian Lopez");
        jFieldNameCoordi.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCoordiRegister.add(jFieldNameCoordi, gridBagConstraints);

        jLNameCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLNameCoordi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLNameCoordi.setText("*Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 99, 0, 0);
        jPCoordiRegister.add(jLNameCoordi, gridBagConstraints);

        jCBProgramCoordi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inge Sistemas" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCoordiRegister.add(jCBProgramCoordi, gridBagConstraints);

        jLProgramCoordi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLProgramCoordi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLProgramCoordi.setText("Programa academico:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCoordiRegister.add(jLProgramCoordi, gridBagConstraints);

        jPRegisterUser.add(jPCoordiRegister, "Coordi");

        jPStudentRegister.setBackground(new java.awt.Color(255, 255, 255));
        jPStudentRegister.setName("StudentRegister"); // NOI18N
        jPStudentRegister.setLayout(new java.awt.GridBagLayout());

        jLNameStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLNameStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLNameStudent.setText("*Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 64;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 99, 0, 0);
        jPStudentRegister.add(jLNameStudent, gridBagConstraints);

        jFieldNameStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldNameStudent.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldNameStudent.setText("Julian Lopez");
        jFieldNameStudent.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPStudentRegister.add(jFieldNameStudent, gridBagConstraints);

        jLCodeStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLCodeStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLCodeStudent.setText("Codigo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPStudentRegister.add(jLCodeStudent, gridBagConstraints);

        jFieldCodeStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldCodeStudent.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldCodeStudent.setText("1046123");
        jFieldCodeStudent.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPStudentRegister.add(jFieldCodeStudent, gridBagConstraints);

        jLTelStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLTelStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLTelStudent.setText("Telefono de contacto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPStudentRegister.add(jLTelStudent, gridBagConstraints);

        jFieldTelStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldTelStudent.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldTelStudent.setText("317123");
        jFieldTelStudent.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPStudentRegister.add(jFieldTelStudent, gridBagConstraints);

        jLEmailStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLEmailStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLEmailStudent.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPStudentRegister.add(jLEmailStudent, gridBagConstraints);

        jFieldEmailStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldEmailStudent.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldEmailStudent.setText("lopez@gmail.com");
        jFieldEmailStudent.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPStudentRegister.add(jFieldEmailStudent, gridBagConstraints);

        jLPasswordStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLPasswordStudent.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLPasswordStudent.setText("Clave:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPStudentRegister.add(jLPasswordStudent, gridBagConstraints);

        jCheckSeePassStudent.setText("Mostrar clave");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 100);
        jPStudentRegister.add(jCheckSeePassStudent, gridBagConstraints);

        jFieldPassWordStudent.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldPassWordStudent.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldPassWordStudent.setText("jPasswordField1");
        jFieldPassWordStudent.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 99, 0, 0);
        jPStudentRegister.add(jFieldPassWordStudent, gridBagConstraints);

        jBtnSaveStudent.setBackground(new java.awt.Color(172, 0, 0));
        jBtnSaveStudent.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jBtnSaveStudent.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSaveStudent.setText("GUARDAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 108, 53, 0);
        jPStudentRegister.add(jBtnSaveStudent, gridBagConstraints);

        jPRegisterUser.add(jPStudentRegister, "Estudiante");

        jPCompanyRegister.setBackground(new java.awt.Color(255, 255, 255));
        jPCompanyRegister.setForeground(new java.awt.Color(255, 255, 255));
        jPCompanyRegister.setMinimumSize(new java.awt.Dimension(700, 381));
        jPCompanyRegister.setName("CompanyRegister"); // NOI18N
        jPCompanyRegister.setPreferredSize(new java.awt.Dimension(700, 381));
        jPCompanyRegister.setLayout(new java.awt.GridBagLayout());

        jLNitCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLNitCompany.setText("*NIT:");
        jLNitCompany.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLNitCompany.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jLNitCompany, gridBagConstraints);

        jFieldNitCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldNitCompany.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldNitCompany.setText("123456789");
        jFieldNitCompany.setToolTipText("");
        jFieldNitCompany.setAutoscrolls(false);
        jFieldNitCompany.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jFieldNitCompany, gridBagConstraints);

        jLNameCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLNameCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLNameCompany.setText("*Nombre Empresa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jLNameCompany, gridBagConstraints);

        jFieldNameCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldNameCompany.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldNameCompany.setText("Empresas Lopez");
        jFieldNameCompany.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jFieldNameCompany, gridBagConstraints);

        jLTelCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLTelCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLTelCompany.setText("Telefono de contacto:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jLTelCompany, gridBagConstraints);

        jFieldTelCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldTelCompany.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldTelCompany.setText("31232323");
        jFieldTelCompany.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jFieldTelCompany, gridBagConstraints);

        jLWebCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLWebCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLWebCompany.setText("Pagina web:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 49;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jLWebCompany, gridBagConstraints);

        jFieldWebCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldWebCompany.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldWebCompany.setText("www.lopez.com");
        jFieldWebCompany.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jFieldWebCompany, gridBagConstraints);

        jLSectorCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLSectorCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLSectorCompany.setText("Sector industrial:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jLSectorCompany, gridBagConstraints);

        jCBSectorCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jCBSectorCompany.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBSectorCompany.setMaximumSize(new java.awt.Dimension(300, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jCBSectorCompany, gridBagConstraints);

        jLEmailCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLEmailCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLEmailCompany.setText("Email:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jLEmailCompany, gridBagConstraints);

        jFieldEmailCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldEmailCompany.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldEmailCompany.setText("lopez@gmail.com");
        jFieldEmailCompany.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jFieldEmailCompany, gridBagConstraints);

        jLPasswordCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLPasswordCompany.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLPasswordCompany.setText("Clave:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 99, 0, 0);
        jPCompanyRegister.add(jLPasswordCompany, gridBagConstraints);

        jFieldPassWordCompany.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jFieldPassWordCompany.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldPassWordCompany.setText("Clave123.");
        jFieldPassWordCompany.setMaximumSize(new java.awt.Dimension(500, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 99, 0, 0);
        jPCompanyRegister.add(jFieldPassWordCompany, gridBagConstraints);

        jCheckSeePassCompany.setText("Mostrar clave");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 100);
        jPCompanyRegister.add(jCheckSeePassCompany, gridBagConstraints);

        jBtnSaveCompany.setBackground(new java.awt.Color(172, 0, 0));
        jBtnSaveCompany.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jBtnSaveCompany.setForeground(new java.awt.Color(255, 255, 255));
        jBtnSaveCompany.setText("GUARDAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 108, 5, 0);
        jPCompanyRegister.add(jBtnSaveCompany, gridBagConstraints);

        jLDatosContacto.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLDatosContacto.setText("Datos de contacto encargado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPCompanyRegister.add(jLDatosContacto, gridBagConstraints);

        jLabel1.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPCompanyRegister.add(jLabel1, gridBagConstraints);

        jFieldNombreAse.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFieldNombreAse.setText("Pepe");
        jFieldNombreAse.setMinimumSize(new java.awt.Dimension(100, 22));
        jFieldNombreAse.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPCompanyRegister.add(jFieldNombreAse, gridBagConstraints);

        jLApellidoAse.setText("Apellido:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        jPCompanyRegister.add(jLApellidoAse, gridBagConstraints);

        jFieldApellidoAse.setText("Lopez");
        jFieldApellidoAse.setMinimumSize(new java.awt.Dimension(100, 22));
        jFieldApellidoAse.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        jPCompanyRegister.add(jFieldApellidoAse, gridBagConstraints);

        jLPuestoAse.setText("Cargo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        jPCompanyRegister.add(jLPuestoAse, gridBagConstraints);

        jFielPuestoAse.setText("Gerente");
        jFielPuestoAse.setMinimumSize(new java.awt.Dimension(100, 22));
        jFielPuestoAse.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        jPCompanyRegister.add(jFielPuestoAse, gridBagConstraints);

        jPRegisterUser.add(jPCompanyRegister, "Empresa");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = -79;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 7, 9);
        jPContent.add(jPRegisterUser, gridBagConstraints);

        jPButtom.setBackground(new java.awt.Color(15, 32, 65));
        jPButtom.setForeground(new java.awt.Color(255, 255, 255));
        jPButtom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jBtnBackSelectUser.setBackground(new java.awt.Color(15, 32, 65));
        jBtnBackSelectUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon2.0/anterior (1).png"))); // NOI18N
        jBtnBackSelectUser.setBorderPainted(false);
        jPButtom.add(jBtnBackSelectUser);

        jPHead.setBackground(new java.awt.Color(236, 230, 240));
        jPHead.setLayout(new javax.swing.BoxLayout(jPHead, javax.swing.BoxLayout.LINE_AXIS));

        lbTitleProyect.setAlignment(java.awt.Label.CENTER);
        lbTitleProyect.setBackground(new java.awt.Color(15, 32, 65));
        lbTitleProyect.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lbTitleProyect.setForeground(new java.awt.Color(255, 255, 255));
        lbTitleProyect.setText("Sistema gestor de proyectos academicos");
        jPHead.add(lbTitleProyect);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPTittleNewUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPHead, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
            .addComponent(jPButtom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPContent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPHead, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPTittleNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPContent, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPButtom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRol;
    private javax.swing.JButton jBtnBackSelectUser;
    private javax.swing.JButton jBtnSaveCompany;
    private javax.swing.JButton jBtnSaveCoordi;
    private javax.swing.JButton jBtnSaveStudent;
    private javax.swing.JComboBox<String> jCBProgramCoordi;
    private javax.swing.JComboBox<String> jCBSectorCompany;
    private javax.swing.JCheckBox jCheckSeePassCompany;
    private javax.swing.JCheckBox jCheckSeePassCoordi;
    private javax.swing.JCheckBox jCheckSeePassStudent;
    private javax.swing.JTextField jFielPuestoAse;
    private javax.swing.JTextField jFieldApellidoAse;
    private javax.swing.JTextField jFieldCodeCoordi;
    private javax.swing.JTextField jFieldCodeStudent;
    private javax.swing.JTextField jFieldEmailCompany;
    private javax.swing.JTextField jFieldEmailCoordi;
    private javax.swing.JTextField jFieldEmailStudent;
    private javax.swing.JTextField jFieldNameCompany;
    private javax.swing.JTextField jFieldNameCoordi;
    private javax.swing.JTextField jFieldNameStudent;
    private javax.swing.JTextField jFieldNitCompany;
    private javax.swing.JTextField jFieldNombreAse;
    private javax.swing.JPasswordField jFieldPassWordCompany;
    private javax.swing.JPasswordField jFieldPassWordCoordi;
    private javax.swing.JPasswordField jFieldPassWordStudent;
    private javax.swing.JTextField jFieldTelCompany;
    private javax.swing.JTextField jFieldTelCoordi;
    private javax.swing.JTextField jFieldTelStudent;
    private javax.swing.JTextField jFieldWebCompany;
    private javax.swing.JLabel jLApellidoAse;
    private javax.swing.JLabel jLCodeCoordi;
    private javax.swing.JLabel jLCodeStudent;
    private javax.swing.JLabel jLDatosContacto;
    private javax.swing.JLabel jLEmailCompany;
    private javax.swing.JLabel jLEmailCoordi;
    private javax.swing.JLabel jLEmailStudent;
    private javax.swing.JLabel jLNameCompany;
    private javax.swing.JLabel jLNameCoordi;
    private javax.swing.JLabel jLNameStudent;
    private javax.swing.JLabel jLNitCompany;
    private javax.swing.JLabel jLPasswordCompany;
    private javax.swing.JLabel jLPasswordCoordi;
    private javax.swing.JLabel jLPasswordStudent;
    private javax.swing.JLabel jLProgramCoordi;
    private javax.swing.JLabel jLPuestoAse;
    private javax.swing.JLabel jLSectorCompany;
    private javax.swing.JLabel jLSelectRol;
    private javax.swing.JLabel jLTelCompany;
    private javax.swing.JLabel jLTelCoordi;
    private javax.swing.JLabel jLTelStudent;
    private javax.swing.JLabel jLTittleNewCompany;
    private javax.swing.JLabel jLTittleNewCompany1;
    private javax.swing.JLabel jLTittleNewStudent;
    private javax.swing.JLabel jLTittleNewUser;
    private javax.swing.JLabel jLWebCompany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPButtom;
    private javax.swing.JPanel jPCompanyInformation;
    private javax.swing.JPanel jPCompanyRegister;
    private javax.swing.JPanel jPContent;
    private javax.swing.JPanel jPCoordiRegister;
    private javax.swing.JPanel jPCoordinatorInformation;
    private javax.swing.JPanel jPHead;
    private javax.swing.JPanel jPRegisterUser;
    private javax.swing.JPanel jPRolInformation;
    private javax.swing.JPanel jPSelecRol;
    private javax.swing.JPanel jPStudentInformation;
    private javax.swing.JPanel jPStudentRegister;
    private javax.swing.JPanel jPTittleNewUser;
    private javax.swing.JRadioButton jRbtnCompany;
    private javax.swing.JRadioButton jRbtnCoordi;
    private javax.swing.JRadioButton jRbtnStudent;
    private javax.swing.JScrollPane jScrolInfoCompany;
    private javax.swing.JScrollPane jScrolInfoCoordi;
    private javax.swing.JScrollPane jScrolInfoStudent;
    private javax.swing.JTextArea jTextAInfoCompany;
    private javax.swing.JTextArea jTextAInfoCoordi;
    private javax.swing.JTextArea jTextAInfoStudent;
    private java.awt.Label lbTitleProyect;
    // End of variables declaration//GEN-END:variables
}
